//! PROBE-MULTI-GROUP-MEMBERSHIP-1 — can ordinary resident objects belong to
//! 2+ groups simultaneously, with groups as views and masks as derived
//! execution artifacts — and does measured #1001-style behavioral recurrence
//! justify compression?
//!
//! **Root order (operator, 2026-08-23):** before inventing a behavioral
//! compression carrier, exhaust the simpler primitive — MANY-TO-MANY GROUP
//! MEMBERSHIP. Think Active Directory:
//!
//! ```text
//!   object has HHTL home            hierarchy gives scope/address
//!   member/memberOf is many-to-many membership gives participation
//!   groups are views                masks give cheap selection
//! ```
//!
//! Do not confuse those three.
//!
//! # What is NOT here (scope fence, enforced by B-FENCE)
//!
//! No `BpeTable`, no `BpeToken`, no vocabulary, no tokenizer, no embedding,
//! no `VectorIndex`, no sequence model, no learner, no transformer, no
//! prompt corpus, no BPE classids, no `bpe_sidecar`/`learned_mask`/
//! `behavior_mask`/`macro_id` fields on any object. "Behavioral BPE" is
//! only the hypothesis that repeated grounded typed subsequences MAY later
//! deserve a reconstructible macro representation. The only architectural
//! record permitted: **BEHAVIORAL COMPRESSION CARRIER: UNDECIDED.**
//!
//! # The two halves
//!
//! - **M-gates** — generic multi-group membership: one resident item in
//!   Group A AND Group B (and addable to C), canonical bytes stationary,
//!   one membership relation with inverse views, view changes never
//!   repacking the population, masks as derived (delete/rebuild-safe)
//!   artifacts, HHTL scope inheriting up/down while pairwise membership
//!   never becomes ancestry.
//! - **B-gates** — behavioral recurrence over #1001-shaped typed receipts
//!   (`BEFORE + TYPED EDIT = AFTER`): measure what repeats, group it as an
//!   ORDERED group over typed operations (order is the new ingredient, not
//!   "language modeling"), verify exact reconstruction, exclude
//!   repeated-but-FAILED behavior (falsifier F6), and answer honestly
//!   whether compression would buy anything.
//!
//! # Honesty box
//!
//! - The behavioral trajectory is generated by a MECHANICAL driver (the
//!   same typed 3-edit pattern applied per reasoning subject, mirroring
//!   #1003's attend→narrow→interrogate loop). Its recurrence is therefore a
//!   property of the driver, deliberately — it proves the MACHINERY
//!   (detection, ordered grouping, exact reconstruction, failure
//!   exclusion), NOT that production behavior recurs. Production-scale
//!   recurrence is unmeasured and stays open; per the root order, if it
//!   turns out too rare, the correct result is NO BPE.
//! - `Membership { member_address, group_address, order }` is a probe-local
//!   shape for measurement, NOT a prescribed production layout.
//! - Nothing minted; no V3/V4 tenant; no classid touched by membership or
//!   grouping (one probe-local classid homes ALL objects and groups alike).

use lance_graph_contract::attention_facet::{AttentionFocusFacet, RowFocusMask};
use lance_graph_contract::facet::{FacetCascade, FacetTier};
use std::collections::HashMap;

/// ONE classid for every addressed thing here — objects AND groups. Groups
/// are objects too (the AD lesson); membership never touches classid.
const PROBE_CLASSID: u32 = 0xFFFF_0011;

fn addr(parent: u8, leaf: u8) -> [u8; 16] {
    FacetCascade {
        facet_classid: PROBE_CLASSID,
        tiers: [
            FacetTier {
                hi: parent,
                lo: leaf,
            },
            FacetTier { hi: 0, lo: 0 },
            FacetTier { hi: 0, lo: 0 },
            FacetTier { hi: 0, lo: 0 },
            FacetTier { hi: 0, lo: 0 },
            FacetTier { hi: 0, lo: 0 },
        ],
    }
    .to_bytes()
}

fn focus(a: &[u8; 16]) -> AttentionFocusFacet {
    AttentionFocusFacet::exact(FacetCascade::from_bytes(a))
}

/// THE one canonical membership relation (probe-local shape, not a layout).
/// `member`/`memberOf` are both views over THIS — never a second truth.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
struct Membership {
    member_address: [u8; 16],
    group_address: [u8; 16],
    /// Optional order/role — `None` for unordered groups; `Some(pos)` for
    /// ordered (behavioral) groups. The ONLY new semantic ingredient.
    order: Option<u16>,
}

/// `members(g)` — a view (filter) over the one relation.
fn members<'a>(rel: &'a [Membership], g: &'a [u8; 16]) -> impl Iterator<Item = &'a Membership> {
    rel.iter().filter(move |m| &m.group_address == g)
}

/// `member_of(x)` — the inverse view over the SAME relation.
fn member_of<'a>(rel: &'a [Membership], x: &'a [u8; 16]) -> impl Iterator<Item = &'a Membership> {
    rel.iter().filter(move |m| &m.member_address == x)
}

// ─── #1001-shaped typed behavioral receipts ─────────────────────────────────

/// A typed view edit (the #1001/#1003 vocabulary, probe-local). Each op is a
/// TYPED transformation of a view plan — never a mask literal, never text.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
enum Op {
    PushBoundAt(u8),
    PushRungBand(u8, u8),
    PushGapSubject(u16),
    Pop,
}

/// One receipt: BEFORE + TYPED EDIT = AFTER, with the #1001 warrant verdict.
/// `granted == false` records an edit whose warrant said NO — it happened,
/// it is retained, and it must never become macro material (falsifier F6).
#[derive(Clone, Copy, PartialEq, Debug)]
struct Receipt {
    before_len: usize,
    op: Op,
    after_len: usize,
    granted: bool,
}

/// Replay a plan-length through one op — the reconstruction rule for this
/// probe's plan state (a selector stack; Push grows it, Pop shrinks it).
fn apply(len: usize, op: Op) -> usize {
    match op {
        Op::Pop => len.saturating_sub(1),
        _ => len + 1,
    }
}

fn main() {
    let mut pass = 0u32;
    let mut gate = |name: &str, ok: bool, detail: String| {
        assert!(ok, "[FAIL] {name} — {detail}");
        println!("  [PASS] {name} — {detail}");
        pass += 1;
    };

    // ═══ Half 1 — generic multi-group membership ═══════════════════════════

    // Resident population: six objects in two HHTL subtrees, plus THREE
    // groups (groups are addressed objects too, in their own region).
    let objects: Vec<[u8; 16]> = vec![
        addr(0x40, 1),
        addr(0x40, 2),
        addr(0x40, 3),
        addr(0x50, 1),
        addr(0x50, 2),
        addr(0x50, 3),
    ];
    let group_a = addr(0x70, 0xA);
    let group_b = addr(0x70, 0xB);
    let group_c = addr(0x70, 0xC);
    let population_before: Vec<[u8; 16]> = objects.clone();

    // The one membership relation. Object 0x40.2 is in BOTH A and B.
    let mut rel: Vec<Membership> = vec![
        Membership {
            member_address: objects[0],
            group_address: group_a,
            order: None,
        },
        Membership {
            member_address: objects[1], // 0x40.2 — the dual-membership item
            group_address: group_a,
            order: None,
        },
        Membership {
            member_address: objects[1], // …also in B
            group_address: group_b,
            order: None,
        },
        Membership {
            member_address: objects[3], // cross-subtree member of A
            group_address: group_a,
            order: None,
        },
        Membership {
            member_address: objects[4],
            group_address: group_b,
            order: None,
        },
    ];

    // ---- M1 — one item, 2+ simultaneous memberships; a third addable ----
    let x = &objects[1];
    let in_before: Vec<[u8; 16]> = member_of(&rel, x).map(|m| m.group_address).collect();
    rel.push(Membership {
        member_address: *x,
        group_address: group_c,
        order: None,
    });
    let in_after: Vec<[u8; 16]> = member_of(&rel, x).map(|m| m.group_address).collect();
    gate(
        "M1 one resident item belongs to A AND B, and C is addable",
        in_before == vec![group_a, group_b]
            && in_after == vec![group_a, group_b, group_c]
            && objects == population_before,
        "memberships {A,B} → {A,B,C} by appending ONE relation row; the object's \
         canonical bytes and every other object are bit-identical throughout"
            .to_string(),
    );

    // ---- M2 — members/memberOf: inverse views over ONE relation ----
    let mut m2_ok = true;
    for g in [&group_a, &group_b, &group_c] {
        for m in members(&rel, g) {
            m2_ok &= member_of(&rel, &m.member_address).any(|r| &r.group_address == g);
        }
    }
    let total_rows = rel.len();
    let via_groups: usize = [&group_a, &group_b, &group_c]
        .iter()
        .map(|g| members(&rel, g).count())
        .sum();
    gate(
        "M2 members/memberOf are inverse views over ONE relation, never two truths",
        m2_ok && via_groups == total_rows,
        format!(
            "every members(g) row answers memberOf(member)∋g; the group views partition \
             all {total_rows} membership rows; both directions are filters over the SAME \
             Vec — no duplicated canonical state exists to diverge"
        ),
    );

    // ---- M3 — masks are DERIVED artifacts: compile, delete, rebuild ----
    // Compile group A's HHTL applicability mask from its members' addresses.
    let compile = |rel: &[Membership], g: &[u8; 16]| -> RowFocusMask {
        let mut m = RowFocusMask::empty();
        for r in members(rel, g) {
            m.insert(focus(&r.member_address));
        }
        m
    };
    let mask_a1 = compile(&rel, &group_a);
    let covered_before: Vec<bool> = objects.iter().map(|o| mask_a1.contains(focus(o))).collect();
    drop(mask_a1); // DELETE the mask entirely…
    let mask_a2 = compile(&rel, &group_a); // …and rebuild from the relation.
    let covered_after: Vec<bool> = objects.iter().map(|o| mask_a2.contains(focus(o))).collect();
    gate(
        "M3 the group mask is a derived execution artifact — delete/rebuild-safe",
        covered_before == covered_after && objects == population_before,
        "compiling, deleting, and recompiling group A's RowFocusMask yields identical \
         coverage; the mask is never a semantic owner — the membership relation is, \
         and the population never moved"
            .to_string(),
    );

    // ---- M4 — view changes never repack the population ----
    let rel_snapshot = rel.clone();
    // Leave group A (remove one membership), then re-join.
    rel.retain(|m| !(m.member_address == objects[0] && m.group_address == group_a));
    let left = member_of(&rel, &objects[0]).count();
    rel.push(Membership {
        member_address: objects[0],
        group_address: group_a,
        order: None,
    });
    gate(
        "M4 joining/leaving groups never moves or repacks resident objects",
        left == 0 && objects == population_before && rel.len() == rel_snapshot.len(),
        "leave + re-join touched ONLY membership rows; all six resident docks are \
         byte- and order-identical (falsifier F12 held)"
            .to_string(),
    );

    // ---- M5 — HHTL scope inherits; pairwise membership is NOT ancestry ----
    let region_40 =
        AttentionFocusFacet::prefix(FacetCascade::from_bytes(&addr(0x40, 0)), 1).expect("depth 1");
    // Scope: a group's applicability at region 0x40.* covers its members
    // there (inheritance DOWN by covers)…
    let a_members_in_scope = members(&rel, &group_a)
        .filter(|m| region_40.covers(focus(&m.member_address)))
        .count();
    // …while the cross-subtree member (0x50.1) belongs WITHOUT any ancestry:
    let cross = members(&rel, &group_a)
        .find(|m| m.member_address == objects[3])
        .expect("cross-subtree member");
    let fx = focus(&cross.member_address);
    let fg = focus(&group_a);
    gate(
        "M5 scope inherits via covers; membership itself never becomes ancestry",
        a_members_in_scope == 2 && !fg.covers(fx) && !fx.covers(fg) && !region_40.covers(fx),
        "region 0x40.* covers 2 of group A's 3 members (applicability inherited down); \
         the third member lives in 0x50.* — neither the group's address nor any region \
         covers it, yet it belongs: GROUP MEMBERSHIP IS RELATION TOPOLOGY, NOT HHTL \
         ANCESTRY"
            .to_string(),
    );

    // ═══ Half 2 — behavioral recurrence over #1001-shaped receipts ═════════

    // A mechanical driver applies the SAME typed attend→narrow→interrogate
    // pattern per reasoning subject (the #1003 loop shape), plus one edit
    // whose warrant said NO (the F6 exclusion subject).
    let subjects: [u16; 4] = [1, 2, 3, 5];
    let mut receipts: Vec<Receipt> = Vec::new();
    let mut len = 0usize;
    for &s in &subjects {
        for op in [
            Op::PushBoundAt(9),
            Op::PushRungBand(1, 2),
            Op::PushGapSubject(s),
        ] {
            let after = apply(len, op);
            receipts.push(Receipt {
                before_len: len,
                op,
                after_len: after,
                granted: true,
            });
            len = after;
        }
        for _ in 0..3 {
            let after = apply(len, Op::Pop);
            receipts.push(Receipt {
                before_len: len,
                op: Op::Pop,
                after_len: after,
                granted: true,
            });
            len = after;
        }
    }
    // The repeated-but-REFUSED edit: attempted twice, warrant said NO both
    // times (an off-field band). It recurs — and must never become a macro.
    for _ in 0..2 {
        receipts.push(Receipt {
            before_len: len,
            op: Op::PushRungBand(9, 9),
            after_len: len, // refused: the plan did not change
            granted: false,
        });
    }

    // ---- B1 — BEFORE + TYPED EDIT = AFTER, replay-verified ----
    let mut replay = 0usize;
    let mut b1_ok = true;
    for r in &receipts {
        b1_ok &= r.before_len == replay;
        if r.granted {
            replay = apply(replay, r.op);
        }
        b1_ok &= r.after_len == replay;
    }
    gate(
        "B1 every receipt reconstructs: BEFORE + TYPED EDIT = AFTER",
        b1_ok && receipts.len() == 26,
        format!(
            "{} receipts replay to the exact final state (len {replay}); refused edits \
             are retained WITH their refusal — the trajectory is the #1001 invariant, \
             not a log",
            receipts.len()
        ),
    );

    // ---- B2 — measure recurrence BEFORE proposing anything ----
    let granted: Vec<&Receipt> = receipts.iter().filter(|r| r.granted).collect();
    let mut op_freq: HashMap<Op, usize> = HashMap::new();
    for r in &granted {
        *op_freq.entry(r.op).or_default() += 1;
    }
    let unique_ops = op_freq.len();
    let repeated_ops = op_freq.values().filter(|&&c| c > 1).count();
    // Repeated subsequences of length 2 and 3+ over the granted op stream.
    let ops: Vec<Op> = granted.iter().map(|r| r.op).collect();
    let mut sub2: HashMap<(Op, Op), usize> = HashMap::new();
    for w in ops.windows(2) {
        *sub2.entry((w[0], w[1])).or_default() += 1;
    }
    let rep2 = sub2.values().filter(|&&c| c > 1).count();
    let mut sub3: HashMap<(Op, Op, Op), usize> = HashMap::new();
    for w in ops.windows(3) {
        *sub3.entry((w[0], w[1], w[2])).or_default() += 1;
    }
    let rep3 = sub3.values().filter(|&&c| c > 1).count();
    gate(
        "B2 recurrence measured: totals, uniques, repeated subsequences",
        !ops.is_empty() && rep2 > 0 && rep3 > 0,
        format!(
            "{} granted transformations, {unique_ops} unique ops ({repeated_ops} \
             repeat); repeated 2-subsequences: {rep2}; repeated 3+-subsequences: \
             {rep3}. HONESTY: this recurrence is a property of the mechanical driver \
             (same pattern per subject) — it proves the detection machinery, NOT that \
             production behavior recurs; that measurement stays open",
            ops.len()
        ),
    );

    // ---- B3 — an ORDERED group over typed ops reconstructs exactly ----
    // The recurrent 3-op pattern becomes an ordered group whose members are
    // op POSITIONS in the receipt stream (references, never copies). Order
    // is the only new ingredient vs an ordinary group.
    let pattern = [Op::PushBoundAt(9), Op::PushRungBand(1, 2)];
    let behavior_group = addr(0x70, 0xE);
    let mut ordered: Vec<Membership> = Vec::new();
    let mut occurrence = 0u16;
    for (i, w) in ops.windows(2).enumerate() {
        if w == pattern {
            for (k, _) in w.iter().enumerate() {
                ordered.push(Membership {
                    member_address: addr(0x60, (i + k) as u8), // the op's address-by-position
                    group_address: behavior_group,
                    order: Some(occurrence * 2 + k as u16),
                });
            }
            occurrence += 1;
        }
    }
    // Reconstruct the pattern occurrences from the ordered group alone.
    let mut by_order: Vec<&Membership> = members(&ordered, &behavior_group).collect();
    by_order.sort_by_key(|m| m.order);
    let reconstructed: Vec<Op> = by_order
        .iter()
        .map(|m| {
            let pos = FacetCascade::from_bytes(&m.member_address).tiers[0].lo as usize;
            ops[pos]
        })
        .collect();
    let expect: Vec<Op> = (0..occurrence as usize).flat_map(|_| pattern).collect();
    gate(
        "B3 an ordered behavioral group reconstructs its op sequence exactly",
        occurrence as usize == subjects.len() && reconstructed == expect,
        format!(
            "the 2-op pattern recurred {occurrence}× (once per subject); the ordered \
             group stores op REFERENCES + positions, and replaying it by order yields \
             the exact typed sequence — order preserved (F3 held), no op copied, no \
             receipt mutated"
        ),
    );

    // ---- B4 — falsifier F6: repeated FAILURE is never macro material ----
    let refused: Vec<&Receipt> = receipts.iter().filter(|r| !r.granted).collect();
    let refused_recurs = refused.len() >= 2 && refused.iter().all(|r| r.op == refused[0].op);
    let macro_candidates: Vec<Op> = op_freq
        .iter()
        .filter(|(_, &c)| c > 1)
        .map(|(&op, _)| op)
        .collect();
    let f6_held = !macro_candidates.contains(&Op::PushRungBand(9, 9));
    gate(
        "B4 a repeated-but-REFUSED edit is excluded from macro candidacy (F6)",
        refused_recurs && f6_held,
        format!(
            "PushRungBand(9,9) recurred {}× and was refused every time; the candidate \
             filter (built over GRANTED receipts only) never sees it — behavior that \
             merely repeats but repeatedly fails cannot be learned",
            refused.len()
        ),
    );

    // ---- B5 — the comparison, and the verdict ----
    let raw_bytes = receipts.len() * core::mem::size_of::<Receipt>();
    let group_bytes = ordered.len() * core::mem::size_of::<Membership>();
    gate(
        "B5 raw vs grouped vs macro compared; BEHAVIORAL COMPRESSION CARRIER: UNDECIDED",
        raw_bytes > 0 && group_bytes > 0,
        format!(
            "raw typed receipts: {} × {}B = {raw_bytes}B (AUTHORITATIVE — groups \
             reference them, never replace them); ordered group: {} membership rows = \
             {group_bytes}B ON TOP of the receipts, so at this scale grouping ADDS \
             cost and buys only addressability of the recurrence. A compressed macro \
             is NOT designed, NOT reserved, NOT minted — the carrier remains \
             UNDECIDED, admissible only under the operator's conditions once \
             production recurrence is actually measured",
            receipts.len(),
            core::mem::size_of::<Receipt>(),
            ordered.len()
        ),
    );

    // ---- B-FENCE — the scope fence, structurally ----
    // Falsifiable form: pin the exact shapes. A tokenizer/embedding/learner
    // smuggled into either type would change these sizes and fail the gate.
    gate(
        "B-FENCE no tokenizer/vocabulary/embedding/learner/sidecar appeared",
        core::mem::size_of::<Membership>() == 36
            && core::mem::size_of::<Receipt>() == 24
            && core::mem::size_of::<Op>() == 4,
        "the entire investigation is two Vecs of Copy rows over addressed docks: no \
         BpeTable, no token universe, no embedding, no ANN, no learner, no \
         bpe_sidecar/learned_mask/behavior_mask/macro_id field on any object, and no \
         classid read or written by membership, grouping, or recurrence detection"
            .to_string(),
    );

    println!("PROBE-MULTI-GROUP-MEMBERSHIP-1: ALL {pass} GATES GREEN");
    println!(
        "report: multi-group membership is PROVEN on the simple primitive — one \
         resident item in 2+ groups simultaneously with a third addable (M1), one \
         canonical membership relation with inverse views (M2), masks as \
         delete/rebuild-safe derived artifacts (M3), zero population movement across \
         joins/leaves (M4), and scope inheriting down while cross-subtree membership \
         stays pure relation topology (M5). Behavioral half: #1001 receipts replay \
         exactly (B1), recurrence is measured not assumed (B2 — driver-recurrence, \
         honestly labelled), an ordered group reconstructs its typed sequence with \
         order preserved (B3), repeated failure is structurally excluded from \
         candidacy (B4), and grouping currently ADDS bytes over raw receipts (B5). \
         BEHAVIORAL COMPRESSION CARRIER: UNDECIDED. If production recurrence turns \
         out too rare, the correct result is NO BPE."
    );
}
