//! PROBE-EV7B-COMMA-ANTIMOIRE — the v2, three-arm falsifier for D-QUANTGATE's
//! coprime requirement (`.claude/plans/weather-substrate-evaluation-v1.md`
//! §3 EV-7b v2; the §8 audit found the v1 spec NOT SOUND on two counts: a
//! self-contradicting instrument — its "or lag-k autocorrelation" fallback is
//! exactly the tool `mu_hydration_probe.rs` (see its `three_gap_distinct_count`
//! doc comment) rules out for a deterministic equidistributed walk, since
//! Pearson autocorrelation mis-measures a near-constant step as periodicity —
//! and a two-arm design that could only prove divisor-vs-coprime arithmetic,
//! never "coprime generically avoids aliasing" vs "4-over-17 is uniquely
//! special").
//!
//! **The claim under test** is D-QUANTGATE's *coprime requirement*: a
//! quantized-layer perturbation phase generated by a stride-`s`-over-`m`
//! modular walk must use a modulus `m` INCOMMENSURATE with the surrounding
//! tile pitch (never a divisor of it, never equal to it) — or the walk
//! aliases against the tile grid, regardless of whether `gcd(s, m) = 1`.
//! This is explicitly **NOT** a claim that stride 4 / modulus 17 (K-22's
//! specific comma, `17 = 4² + 1`) is uniquely special; arm (c) below uses a
//! DIFFERENT coprime stride over the SAME incommensurate modulus, which is
//! what separates "any coprime stride over an incommensurate modulus avoids
//! aliasing" from "4 is magic".
//!
//! **Wording fix carried from the v2 spec (loosens K-22's phrasing):** the
//! comma walk (stride 4 over 17) is PERIODIC with period 17 — it is a
//! *permutation* of `Z_17`, not aperiodic in the mathematical sense. K-22's
//! "aperiodic" means *incommensurate with the 16-pitch* (17 neither divides
//! nor is a multiple of the tile pitch 16), not "has no period at all".
//!
//! **Instrument, pinned to ONE:** a 2-D DFT of the perturbation field.
//! Statistic = energy at the FIXED tile-pitch bin `(U0, 0)`,
//! `U0 = FIELD_SIZE / TILE_PITCH`, divided by the MEDIAN energy over every
//! OTHER non-DC bin — a unitless peak-to-median ratio. `U0` is derived ONLY
//! from `FIELD_SIZE` and `TILE_PITCH`, never from any arm's own
//! `(stride, modulus)` — the same fixed bin is checked identically across
//! all three arms, so nothing is cherry-picked per arm.
//!
//! **Why `FIELD_SIZE = 272` (not a smaller, cheaper power of two):**
//! `272 = 16 × 17 = lcm(TILE_PITCH, COMMA_MODULUS)`. This is the SMALLEST
//! field size that both:
//!  - lets the REGULAR arm's comb land EXACTLY on `U0` (harmonic 1 of a
//!    period-16 signal inside a 272-wide field is bin `272/16 = 17 = U0`);
//!  - lets the COMMA/COPRIME2 arms' comb land on bins that are PROVABLY
//!    DISJOINT from `U0` (harmonics of a period-17 signal inside a 272-wide
//!    field sit at multiples of `272/17 = 16`; since `gcd(16,17)=1`, `17` is
//!    never a nonzero integer multiple of `16` — checked directly in
//!    `tests::u0_is_never_a_comma_harmonic`, not merely asserted here).
//! A smaller field (e.g. 64, not a multiple of 17) would leave the comma
//! arm's true fundamental at the NON-integer bin `64/17 ≈ 3.76`, which is
//! close enough to a plausible `U0` choice that ordinary DFT spectral
//! leakage could smear a non-trivial, hard-to-bound fraction of its energy
//! onto the neighbouring integer bin — turning "does the comma arm alias"
//! into a leakage-magnitude question this file cannot answer without
//! actually running the numbers. `FIELD_SIZE = 272` removes that ambiguity:
//! the separation below is EXACT (up to floating-point rounding), not a
//! probabilistic estimate of leakage.
//!
//! **Field construction (identical formula for all three arms — only
//! `(stride, modulus)` differ, which is what makes the comparison
//! non-cherry-picked):**
//!   `addr(x,y) = y*FIELD_SIZE + x` — the same row-major address convention
//!   `fire_forget_replay_probe.rs`'s `Region::addr` uses;
//!   `phase_walk(addr) = (stride * (addr % modulus)) % modulus` — the exact
//!   shape of `fire_forget_replay_probe.rs::comma_phase` and the comma-family
//!   walks in `morton_shift_motion_probe.rs`, generalized to take
//!   `(stride, modulus)` as parameters instead of hardcoding K-22's pair;
//!   `field(x,y) = phase_walk(addr(x,y)) + noise(x,y)`, where `noise(x,y)` is
//!   a FIXED broadband component — same salt, same address, IDENTICAL across
//!   all three arms — added on top of the (now exactly commensurate, for
//!   EVERY arm, given `FIELD_SIZE`'s construction) coherent comb.
//!
//! **Why the noise floor is still needed even with an exact comb
//! separation:** without it, EVERY arm's phase-only field is an exactly
//! periodic, row-invariant signal (see the LCM reasoning above), so its DFT
//! is EXACTLY zero (up to floating-point rounding noise) at every
//! non-harmonic bin — including, for the comma/coprime2 arms, at `U0`
//! itself. Both the numerator (`U0`'s energy) and the "median over non-DC
//! bins" denominator would then be dominated by floating-point ROUNDING
//! ARTIFACTS rather than a real physical quantity, making the ratio for the
//! comma/coprime2 arms an unpredictable function of numerical noise instead
//! of a meaningful measurement. Adding a REAL, fixed broadband floor
//! (`noise(x,y)`, arm-independent) makes both `U0`'s energy and the median
//! dominated by genuine, well-defined noise power instead — turning the
//! comma/coprime2 ratio into an ordinary "is this one bin an outlier
//! relative to ~74k other same-distribution bins" statistical question,
//! which is what the instrument is actually meant to measure. The regular
//! arm's peak still dominates regardless of the noise floor's presence,
//! since its coherent comb concentrates comparable total power into a
//! handful of bins instead of spreading it across the whole field (see the
//! bars' reasoning below).
//!
//! **Three arms, pre-registered:**
//!  (a) REGULAR — `stride=1, modulus=TILE_PITCH(16)`. The modulus EQUALS the
//!      tile pitch, so it commensurately divides `FIELD_SIZE`
//!      (`272 = 17×16`): `addr % 16 = (y*272 + x) % 16 = x % 16` for every
//!      row (since `272 % 16 == 0`), collapsing the coherent component to a
//!      pure period-16 ramp in `x`, IDENTICAL across all 272 rows. This is
//!      the worst-case "regular stride that divides the tile pitch"
//!      perturbation: every tile-row's phase pattern repeats exactly, and
//!      its fundamental harmonic sits EXACTLY at `(U0, 0)`.
//!  (b) COMMA — `stride=4, modulus=17` (K-22's discrete Pythagorean comma).
//!      `17` divides `FIELD_SIZE` too (`272 = 16×17`), so this arm is ALSO
//!      exactly row-invariant (`addr % 17 = x % 17`) — but its comb sits on
//!      harmonics of `272/17 = 16`, a set that PROVABLY EXCLUDES `U0 = 17`
//!      (since `17` is never a multiple of `16`). Row-invariance here is a
//!      feature of this specific `FIELD_SIZE`, not evidence of "genuine 2-D
//!      coupling" — what matters for the claim under test is which BINS the
//!      energy concentrates on, and those bins are disjoint from `U0` by
//!      construction, exactly, not approximately.
//!  (c) A DIFFERENT COPRIME — `stride=5, modulus=17` (same incommensurate
//!      modulus as (b), a different stride; `gcd(5,17)=1` since 17 is
//!      prime). Shares the same disjoint-comb guarantee as (b) — proves the
//!      coprime-with-incommensurate-modulus property generalizes past
//!      stride 4 specifically, which is what separates "any coprime stride
//!      over 17 avoids the tile-pitch bin" from "4-over-17 is magic".
//!
//! **Bars, pre-registered BEFORE the run:** `R_HI = 150.0`, `R_LO = 15.0`,
//! with `R_HI >= 10.0 * R_LO` (150 >= 150, held as an explicit runtime
//! assertion so the pre-registration cannot silently drift). Reasoning
//! (order-of-magnitude, not a measured number — this file has NOT been
//! compiled or run; edit-only worker, orchestrator compiles/runs centrally):
//! the regular arm concentrates essentially its entire coherent power into
//! ~8 harmonic bins (out of `272² - 1 ≈ 74 000` non-DC bins total), so even
//! a crude "comparable total power, ~8 bins vs ~74 000 bins" concentration
//! argument alone predicts a peak-to-median ratio in the tens of thousands —
//! `R_HI = 150` clears with very wide margin. For the comma/coprime2 arms,
//! `U0`'s energy is (by the exact-disjoint-comb argument above) PURELY the
//! noise floor's contribution at that one bin — an ordinary single draw from
//! the same distribution the ~74 000-bin median is computed over, so its
//! ratio to that median should sit near 1 with only ordinary statistical
//! spread; `R_LO = 15` gives generous headroom against that spread being
//! larger than typically expected. If the measured ratios land outside these
//! bars, the correct response is a recorded amendment to the bars (per the
//! plan's own discipline), not a silent re-pin.
//!
//! **Silence-side fixture guard (the v1 defect this closes — it guarded only
//! the can-fire half):** the comma arm's PHASE COMPONENT ALONE (no noise —
//! see `build_phase_only`) must carry NONZERO total energy
//! (`Σ phase(x,y)² > 0`). Checked in isolation from the (arm-independent)
//! noise floor so the guard actually tests the perturbation generator, not
//! the noise floor that would trivially keep the combined field nonzero even
//! if `phase_walk` had a bug that made it identically zero. "No peak" must
//! not silently mean "no signal".
//!
//! std-only, fully deterministic — no RNG. `noise(x,y)` is a stateless hash
//! of `(x,y)`, not a seeded stream, so there is nothing to seed and no run-
//! to-run variance. Prints `EV7B …` greppable lines to stderr, one PASS/FAIL
//! line per bar.

use std::f64::consts::PI;

/// Field axis: FIELD_SIZE × FIELD_SIZE cells. `272 = lcm(TILE_PITCH, 17)` —
/// see the module doc's "Why FIELD_SIZE = 272" section for why this exact
/// value (not a smaller, cheaper power of two) is what makes the
/// regular-vs-coprime bin separation EXACT rather than a leakage estimate.
const FIELD_SIZE: usize = 272;
/// The surrounding tile grid's pitch — K-22's 16-pitch (matches the v2
/// spec's own wording-fix phrase "incommensurate with the 16-pitch").
const TILE_PITCH: usize = 16;
/// The fixed target bin: horizontal spatial frequency corresponding to
/// period = TILE_PITCH, zero vertical frequency. Derived ONLY from
/// FIELD_SIZE and TILE_PITCH — never from any arm's own generative
/// parameters — so the same bin is checked identically for all three arms.
const U0: usize = FIELD_SIZE / TILE_PITCH; // = 17

// Arm (a) — regular: modulus EQUALS the tile pitch (commensurate).
const REGULAR_STRIDE: u32 = 1;
const REGULAR_MODULUS: u32 = TILE_PITCH as u32; // 16

// Arm (b) — the comma walk (K-22): stride 4 over 17.
const COMMA_STRIDE: u32 = 4;
const COMMA_MODULUS: u32 = 17;

// Arm (c) — a different coprime stride over the SAME incommensurate
// modulus. `gcd(5, 17) = 1` since 17 is prime.
const COPRIME2_STRIDE: u32 = 5;
const COPRIME2_MODULUS: u32 = 17;

/// Broadband noise-floor amplitude scale — roughly matches the phase walk's
/// own value range (0..17) so neither term structurally dominates the other
/// by construction. See the module doc's noise-floor reasoning.
const NOISE_AMPLITUDE: f64 = 17.0;
/// Salt for the noise hash ("EV7BNOIS" as big-endian bytes) — arm-
/// independent, so the SAME noise realization backs every arm.
const NOISE_SALT: u64 = 0x_4556_3742_4E4F_4953;

/// Pre-registered bars (stated BEFORE the run, per the v2 spec's discipline;
/// see the module doc for the reasoning behind these specific values).
const R_HI: f64 = 150.0; // regular arm's ratio must clear this
const R_LO: f64 = 15.0; // comma / coprime arms' ratios must stay under this

/// SplitMix64 finalizer (stateless), same generator family as
/// `fire_forget_replay_probe.rs::mix` — used only to derive the fixed,
/// arm-independent noise floor from `(x, y)`, never as a stateful stream.
fn mix64(mut z: u64) -> u64 {
    z = z.wrapping_add(0x9E37_79B9_7F4A_7C15);
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Row-major address, identical convention to
/// `fire_forget_replay_probe.rs::Region::addr`.
fn addr(x: usize, y: usize) -> u64 {
    (y as u64) * (FIELD_SIZE as u64) + (x as u64)
}

/// The shared phase-walk formula: `(stride * (addr % modulus)) % modulus`.
/// Identical shape to `fire_forget_replay_probe.rs::comma_phase` and the
/// comma-family walks in `morton_shift_motion_probe.rs`, generalized to take
/// `(stride, modulus)` so the SAME formula produces all three arms — the
/// arms differ only in their two integer parameters, never in the formula
/// itself.
fn phase_walk(addr: u64, stride: u32, modulus: u32) -> u32 {
    let r = (addr % modulus as u64) as u32;
    stride.wrapping_mul(r) % modulus
}

/// Fixed, arm-independent broadband noise floor at `(x, y)`, in
/// `[0, NOISE_AMPLITUDE)`. Deterministic hash, not a seeded RNG stream.
fn noise_at(x: usize, y: usize) -> f64 {
    let h = mix64(addr(x, y) ^ NOISE_SALT);
    ((h & 0xFFFF) as f64 / 65536.0) * NOISE_AMPLITUDE
}

/// The coherent phase component ALONE, no noise — used by the silence-side
/// fixture guard, which must test the PERTURBATION signal in isolation from
/// the noise floor (see the module doc).
fn build_phase_only(stride: u32, modulus: u32) -> Vec<f64> {
    let mut field = vec![0.0f64; FIELD_SIZE * FIELD_SIZE];
    for y in 0..FIELD_SIZE {
        for x in 0..FIELD_SIZE {
            field[y * FIELD_SIZE + x] = phase_walk(addr(x, y), stride, modulus) as f64;
        }
    }
    field
}

/// Full field = coherent phase + the shared broadband noise floor. This is
/// the input to the 2-D DFT ratio measurement.
fn build_field(stride: u32, modulus: u32) -> Vec<f64> {
    let mut field = build_phase_only(stride, modulus);
    for y in 0..FIELD_SIZE {
        for x in 0..FIELD_SIZE {
            field[y * FIELD_SIZE + x] += noise_at(x, y);
        }
    }
    field
}

/// Separable 2-D DFT (row pass then column pass) — mathematically identical
/// to a direct 2-D DFT, `O(FIELD_SIZE^3)` instead of `O(FIELD_SIZE^4)`.
/// Returns `energy[v * FIELD_SIZE + u] = |X(u,v)|^2` for every bin.
fn dft2d_energy(field: &[f64]) -> Vec<f64> {
    let n = FIELD_SIZE;
    // Row pass: row_{re,im}[y][u] = 1-D DFT of row y over x.
    let mut row_re = vec![0.0f64; n * n];
    let mut row_im = vec![0.0f64; n * n];
    for y in 0..n {
        for u in 0..n {
            let mut re = 0.0f64;
            let mut im = 0.0f64;
            for x in 0..n {
                let angle = -2.0 * PI * (u * x) as f64 / n as f64;
                let v = field[y * n + x];
                re += v * angle.cos();
                im += v * angle.sin();
            }
            row_re[y * n + u] = re;
            row_im[y * n + u] = im;
        }
    }
    // Column pass: energy[v][u] = |1-D DFT over y of row_dft[y][u]|^2.
    let mut energy = vec![0.0f64; n * n];
    for u in 0..n {
        for v in 0..n {
            let mut re = 0.0f64;
            let mut im = 0.0f64;
            for y in 0..n {
                let angle = -2.0 * PI * (v * y) as f64 / n as f64;
                let c = angle.cos();
                let s = angle.sin();
                let rre = row_re[y * n + u];
                let rim = row_im[y * n + u];
                // Complex multiply: (rre + i*rim) * (c + i*s).
                re += rre * c - rim * s;
                im += rre * s + rim * c;
            }
            energy[v * n + u] = re * re + im * im;
        }
    }
    energy
}

/// The pinned statistic: energy at the fixed tile-pitch bin `(U0, 0)`
/// divided by the median energy over every OTHER non-DC bin. `(U0, 0)`
/// itself stays IN the pool the median is drawn from (it is a non-DC bin
/// like any other) — only the true DC bin `(0, 0)` is excluded.
fn tile_pitch_ratio(energy: &[f64]) -> f64 {
    let n = FIELD_SIZE;
    let target = energy[U0]; // v=0, u=U0
    let mut others: Vec<f64> = Vec::with_capacity(n * n - 1);
    for v in 0..n {
        for u in 0..n {
            if u == 0 && v == 0 {
                continue; // exclude DC only
            }
            others.push(energy[v * n + u]);
        }
    }
    others.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let mid = others.len() / 2;
    let median = if others.len() % 2 == 0 {
        (others[mid - 1] + others[mid]) / 2.0
    } else {
        others[mid]
    };
    // Defensive floor: avoid a literal 0.0/0.0 -> NaN if every "should be
    // near-zero" bin happened to land on exact fp zero. With the noise floor
    // added this should never trigger in practice; kept as a guard, not
    // relied on.
    target / median.max(f64::MIN_POSITIVE)
}

/// Total energy of a field: `Σ field(x,y)²`. Used by the silence-side
/// fixture guard on the coherent-phase-only field (see `build_phase_only`).
fn total_energy(field: &[f64]) -> f64 {
    field.iter().map(|v| v * v).sum()
}

fn main() {
    // Pre-registration self-check: the ratio invariant must hold BEFORE any
    // measurement runs, or the bars themselves are inconsistent.
    assert!(
        R_HI >= 10.0 * R_LO,
        "pre-registration violated: R_HI ({R_HI}) must be >= 10 * R_LO ({R_LO})"
    );

    let regular_field = build_field(REGULAR_STRIDE, REGULAR_MODULUS);
    let comma_field = build_field(COMMA_STRIDE, COMMA_MODULUS);
    let coprime2_field = build_field(COPRIME2_STRIDE, COPRIME2_MODULUS);

    let regular_ratio = tile_pitch_ratio(&dft2d_energy(&regular_field));
    let comma_ratio = tile_pitch_ratio(&dft2d_energy(&comma_field));
    let coprime2_ratio = tile_pitch_ratio(&dft2d_energy(&coprime2_field));

    eprintln!(
        "EV7B field_size={FIELD_SIZE} tile_pitch={TILE_PITCH} u0={U0} r_hi={R_HI} r_lo={R_LO}"
    );
    eprintln!(
        "EV7B arm=regular stride={REGULAR_STRIDE} modulus={REGULAR_MODULUS} ratio={regular_ratio:.6e}"
    );
    eprintln!(
        "EV7B arm=comma stride={COMMA_STRIDE} modulus={COMMA_MODULUS} ratio={comma_ratio:.6e}"
    );
    eprintln!(
        "EV7B arm=coprime2 stride={COPRIME2_STRIDE} modulus={COPRIME2_MODULUS} ratio={coprime2_ratio:.6e}"
    );

    // Bar 1 — can-fire: the regular (divisor, commensurate-modulus) arm must
    // alias: ratio >= R_HI.
    let bar1 = regular_ratio >= R_HI;
    eprintln!(
        "EV7B BAR1 regular_aliases: ratio={regular_ratio:.6e} >= R_HI={R_HI} -> {}",
        if bar1 { "PASS" } else { "FAIL" }
    );

    // Bar 2 — can-stay-silent: the comma arm must NOT alias: ratio <= R_LO.
    let bar2 = comma_ratio <= R_LO;
    eprintln!(
        "EV7B BAR2 comma_silent: ratio={comma_ratio:.6e} <= R_LO={R_LO} -> {}",
        if bar2 { "PASS" } else { "FAIL" }
    );

    // Bar 3 — the SAME silence under a DIFFERENT coprime stride over the
    // SAME incommensurate modulus — separates "coprime + incommensurate
    // modulus generically avoids aliasing" from "stride 4 specifically".
    let bar3 = coprime2_ratio <= R_LO;
    eprintln!(
        "EV7B BAR3 coprime2_silent: ratio={coprime2_ratio:.6e} <= R_LO={R_LO} -> {}",
        if bar3 { "PASS" } else { "FAIL" }
    );

    // Bar 4 — silence-side fixture guard: the comma arm's PHASE COMPONENT
    // ALONE (no noise) must carry nonzero total energy. "No peak at the
    // tile-pitch bin" must not silently mean "no perturbation signal at
    // all" — a degenerate all-zero phase generator would trivially clear
    // bar 2 for the wrong reason.
    let comma_phase_total = total_energy(&build_phase_only(COMMA_STRIDE, COMMA_MODULUS));
    let bar4 = comma_phase_total > 0.0;
    eprintln!(
        "EV7B BAR4 comma_fixture_nonzero: phase_total_energy={comma_phase_total:.6e} -> {}",
        if bar4 { "PASS" } else { "FAIL" }
    );
    // Same guard for the second coprime arm too, cheaply — not the v2
    // spec's literal wording ("the comma arm's total perturbation energy"),
    // but free extra rigor since it shares the guard helper.
    let coprime2_phase_total = total_energy(&build_phase_only(COPRIME2_STRIDE, COPRIME2_MODULUS));
    eprintln!(
        "EV7B BAR4b coprime2_fixture_nonzero (extra, not spec-required): phase_total_energy={coprime2_phase_total:.6e} -> {}",
        if coprime2_phase_total > 0.0 { "PASS" } else { "FAIL" }
    );

    let overall = bar1 && bar2 && bar3 && bar4;
    eprintln!("EV7B OVERALL {}", if overall { "PASS" } else { "FAIL" });
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pre-registration invariant: R_HI >= 10 * R_LO, checked independently
    /// of `main`'s runtime assertion (so a test run alone still catches a
    /// drifted bar pair without needing to execute `main`).
    #[test]
    fn bars_satisfy_the_ten_x_separation() {
        assert!(
            R_HI >= 10.0 * R_LO,
            "R_HI ({R_HI}) must be >= 10 * R_LO ({R_LO})"
        );
    }

    /// FIELD_SIZE must be an EXACT common multiple of TILE_PITCH and the
    /// comma modulus — this is what the whole exact-disjoint-comb argument
    /// rests on, checked directly rather than merely asserted in prose.
    #[test]
    fn field_size_is_a_common_multiple_of_tile_pitch_and_comma_modulus() {
        assert_eq!(FIELD_SIZE % TILE_PITCH, 0);
        assert_eq!(FIELD_SIZE % (COMMA_MODULUS as usize), 0);
        assert_eq!(FIELD_SIZE % (COPRIME2_MODULUS as usize), 0);
    }

    /// The mathematical core of the whole design: `U0` (the regular arm's
    /// harmonic-1 bin) is NEVER an integer multiple of `FIELD_SIZE /
    /// COMMA_MODULUS` (the comma arm's harmonic spacing) — i.e. the comma
    /// arm's comb structurally cannot land on `U0`. Two-sided against a real
    /// colliding modulus (the regular arm's own 16, see below) rather than
    /// merely asserted in prose, since a hand-derived counter-example is
    /// exactly the kind of claim this file's own falsifiability discipline
    /// says must be exercised, not asserted.
    #[test]
    fn u0_is_never_a_comma_harmonic() {
        let comma_harmonic_spacing = FIELD_SIZE / (COMMA_MODULUS as usize); // 16
        assert_ne!(comma_harmonic_spacing, 0);
        assert_ne!(
            U0 % comma_harmonic_spacing,
            0,
            "U0={U0} must NOT be a multiple of the comma harmonic spacing {comma_harmonic_spacing}"
        );
        // Silence-side twin: the REGULAR arm's own modulus (16) DOES
        // collide — its harmonic spacing is `272/16 = 17 = U0` exactly
        // (harmonic 1 IS the target bin). This proves the check above can
        // distinguish the colliding case (modulus=16) from the
        // non-colliding one (modulus=17), not just always report
        // "disjoint" regardless of input. (17 is prime, so among small
        // divisors of FIELD_SIZE only spacing=17 — i.e. modulus=16 — or the
        // degenerate spacing=1 collide with U0=17; modulus=16 is the
        // non-degenerate one and is also the file's own REGULAR_MODULUS.)
        let regular_harmonic_spacing = FIELD_SIZE / (REGULAR_MODULUS as usize); // 17
        assert_eq!(
            U0 % regular_harmonic_spacing,
            0,
            "sanity: the regular arm's own modulus (16) must collide with U0"
        );
    }

    /// The comma walk (K-22: stride 4 over 17) is a full permutation of
    /// Z_17 — the discrete Pythagorean comma property. Two-sided by
    /// construction: `seen.iter().all(|&s| s)` fails on any non-bijective
    /// walk (e.g. a non-coprime stride), so this is not implied by the code
    /// under test — a stride sharing a factor with 17 would break it.
    #[test]
    fn comma_walk_is_a_full_permutation_of_z17() {
        let mut seen = [false; 17];
        for k in 0..17u64 {
            let w = phase_walk(k, COMMA_STRIDE, COMMA_MODULUS) as usize;
            assert!(!seen[w], "comma walk repeated residue {w} at k={k}");
            seen[w] = true;
        }
        assert!(seen.iter().all(|&s| s));
    }

    /// The second coprime arm (stride 5 over 17) is ALSO a full permutation
    /// of Z_17 — proving `gcd(5,17)=1` holds structurally, not just
    /// asserted in the doc comment.
    #[test]
    fn coprime2_walk_is_a_full_permutation_of_z17() {
        let mut seen = [false; 17];
        for k in 0..17u64 {
            let w = phase_walk(k, COPRIME2_STRIDE, COPRIME2_MODULUS) as usize;
            assert!(!seen[w], "coprime2 walk repeated residue {w} at k={k}");
            seen[w] = true;
        }
        assert!(seen.iter().all(|&s| s));
    }

    /// The regular arm's collapse to pure-x dependency is a consequence of
    /// `FIELD_SIZE % TILE_PITCH == 0`, not an assumption — checked directly,
    /// which is what makes arm (a)'s expected aliasing signature
    /// (constant-across-rows) a proven property of this file's own
    /// constants rather than an unverified claim in prose.
    #[test]
    fn regular_arm_phase_depends_only_on_x() {
        assert_eq!(
            FIELD_SIZE % TILE_PITCH,
            0,
            "field size must be a tile-pitch multiple"
        );
        for y in [0usize, 1, 100, 271] {
            for x in [0usize, 5, 15, 130, 271] {
                let a = phase_walk(addr(x, y), REGULAR_STRIDE, REGULAR_MODULUS);
                let b = phase_walk(addr(x, 0), REGULAR_STRIDE, REGULAR_MODULUS);
                assert_eq!(
                    a, b,
                    "regular arm must be row-invariant at x={x} (y={y} vs y=0)"
                );
            }
        }
    }

    /// The comma arm is ALSO row-invariant at this FIELD_SIZE (a consequence
    /// of `FIELD_SIZE % COMMA_MODULUS == 0`) — the module doc's explicit
    /// point that row-invariance here is a property of the chosen field
    /// size, not evidence of "genuine 2-D coupling"; what actually separates
    /// the arms is which BINS their (row-invariant) combs land on.
    #[test]
    fn comma_arm_phase_also_depends_only_on_x_at_this_field_size() {
        assert_eq!(FIELD_SIZE % (COMMA_MODULUS as usize), 0);
        for y in [0usize, 1, 100, 271] {
            for x in [0usize, 5, 15, 130, 271] {
                let a = phase_walk(addr(x, y), COMMA_STRIDE, COMMA_MODULUS);
                let b = phase_walk(addr(x, 0), COMMA_STRIDE, COMMA_MODULUS);
                assert_eq!(
                    a, b,
                    "comma arm must be row-invariant at x={x} (y={y} vs y=0) for FIELD_SIZE=272"
                );
            }
        }
    }

    /// Silence-side guard, unit-level: the comma arm's phase-only field is
    /// genuinely nonzero (proves `build_phase_only` + `phase_walk` are wired
    /// correctly, independent of the DFT machinery).
    #[test]
    fn comma_phase_only_field_is_nonzero() {
        let field = build_phase_only(COMMA_STRIDE, COMMA_MODULUS);
        assert!(total_energy(&field) > 0.0);
        // Anti-vacuity: a MAJORITY of cells must be nonzero too — a field
        // that is all-zero except one stray cell would clear `> 0.0` for
        // the wrong reason.
        let nonzero = field.iter().filter(|&&v| v != 0.0).count();
        assert!(
            nonzero * 2 > field.len(),
            "comma phase field must be nonzero on a majority of cells, got {nonzero}/{}",
            field.len()
        );
    }

    /// Can-it-STAY-SILENT twin for the same guard: with an intentionally
    /// degenerate (stride=0) walk, the phase field IS all-zero — proving the
    /// guard's `> 0.0` check is not itself vacuously true for any input.
    #[test]
    fn zero_stride_walk_is_the_genuine_silent_case() {
        let field = build_phase_only(0, COMMA_MODULUS);
        assert_eq!(total_energy(&field), 0.0);
    }

    /// DFT sanity: the DC bin (0,0) equals the (squared) sum of the field —
    /// a basic Parseval-adjacent correctness check on `dft2d_energy` itself,
    /// independent of any arm-specific reasoning.
    #[test]
    fn dc_bin_equals_squared_field_sum() {
        let field = build_field(COMMA_STRIDE, COMMA_MODULUS);
        let sum: f64 = field.iter().sum();
        let energy = dft2d_energy(&field);
        let dc = energy[0];
        assert!(
            (dc - sum * sum).abs() < 1e-6 * (sum * sum).abs().max(1.0),
            "DC bin ({dc}) must equal (sum of field)^2 ({}), field sum={sum}",
            sum * sum
        );
    }

    /// The regular arm's tile-pitch-bin ratio must clear R_HI, and the
    /// comma arm's must stay under R_LO — a can-fire vs can-be-silent
    /// comparison computed directly, independent of the printed PASS/FAIL
    /// lines in `main`. This is the most expensive test in the file
    /// (O(FIELD_SIZE^3) per arm, FIELD_SIZE=272) — it duplicates `main`'s
    /// own computation deliberately, so a `cargo test` run alone (without
    /// ever running the example binary) still gates the pre-registered bars.
    #[test]
    fn regular_ratio_clears_comma_ratio_by_the_pre_registered_margin() {
        let regular_ratio =
            tile_pitch_ratio(&dft2d_energy(&build_field(REGULAR_STRIDE, REGULAR_MODULUS)));
        let comma_ratio =
            tile_pitch_ratio(&dft2d_energy(&build_field(COMMA_STRIDE, COMMA_MODULUS)));
        assert!(
            regular_ratio >= R_HI,
            "regular arm ratio {regular_ratio:.3e} did not clear R_HI={R_HI}"
        );
        assert!(
            comma_ratio <= R_LO,
            "comma arm ratio {comma_ratio:.3e} did not stay under R_LO={R_LO}"
        );
    }
}
