//! PROBE-SPLAT-μ-HYDRATION-RHO — leg 1 (board `E-3DGS-MU-HYDRATION-1`).
//!
//! Measures whether `address(Morton-rank) + φ-phase` predicts a 3DGS
//! gaussian's position `μ` better than chance. The 3DGS↔gridlake
//! presumption's one net-new claim is that `μ` can be ADDRESS-DERIVED
//! instead of stored — position = a deterministic φ-phase of a sequential
//! index `n` (0 stored bits) plus a stored residual. The crux the
//! convergence-architect flagged: the φ-phase device needs a *sequential*
//! index `n` — motion has one (path/frame index, see `hevc_headtohead.rs`'s
//! ∞-PSNR tautology on model-matched content), but a **static** gaussian
//! cloud does not. Without a natural sequential index, the best available
//! substitute is spatial-locality addressing (Morton order over quantized
//! `μ`), and this probe asks whether φ-phase-at-Morton-rank predicts
//! position on such an address.
//!
//! EXPECTED per the convergence-architect: the **CONTROL** set (μ
//! literally generated by the φ-hemisphere lift, `HemispherePoint::lift`)
//! hydrates near-fully (`rho → 1`) — the on-manifold tautology, structurally
//! the same shape as `hevc_headtohead.rs`'s ∞ PSNR on a self-generated
//! scene. The **NON-φ** set — a structured-synthetic field built from
//! random axis-aligned "surface" slabs with noise, mimicking real 3DGS
//! scene structure (surfaces + noise) without ever being φ-placed — should
//! NOT hydrate (`rho → 0`, `escalation → 1`): address + φ-phase predicts no
//! better than a random index assignment, so the residual must be stored at
//! ~full precision — ordinary SoA, not a hydration win. If confirmed, the
//! "address-derived μ" seam DROPS for static scenes: it is motion-only.
//!
//! This is a synthetic-structured falsifier, NOT a trained Inria scene —
//! wiring `splat3d::read_ply` against a real `.ply` is the named v2. The
//! structure here is adversarially realistic (surfaces + noise, never
//! φ-placed), not a strawman.
//!
//! The **comma anti-moiré fence** (board `E-COMMA-PERTURBATION-PHASE-1`) is
//! measured here too, orthogonally: it confirms the φ / coprime-walk phase
//! is aperiodic (no moiré against the tile grid) regardless of the
//! hydration outcome above — via the Steinhaus three-gap theorem on the
//! golden rotation `{n·φ}` (sorted arcs take `≤ 3` distinct lengths — the
//! correct low-discrepancy certificate) and the stride-4-over-17 coprime
//! walk (a full permutation of the 17 residues, `gcd(4,17)=1`, the discrete
//! comma).
//!
//! std-only + the `helix::placement` public API. Deterministic
//! (SplitMix64, no `rand`). Prints machine-greppable `MUHYD ...` lines to
//! stderr; the orchestrator adjudicates the numbers.

use helix::placement::HemispherePoint;

/// Number of gaussians in each synthetic point set.
const N: usize = 4096;
/// Per-axis Morton quantization grid resolution (64 → 6 bits/axis, 18-bit code).
const GRID: usize = 64;
/// Seed — "MUHYDRA1" in ASCII-ish hex, per the brief.
const SEED: u64 = 0x_4D55_4859_4452_4131;

/// SplitMix64 — copied verbatim from `hevc_headtohead.rs` (same generator +
/// seed-family convention used across the helix probes; no `rand` dep).
struct SplitMix64(u64);
impl SplitMix64 {
    fn new(seed: u64) -> Self {
        Self(seed)
    }
    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
    fn unit(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }
    fn range(&mut self, lo: f64, hi: f64) -> f64 {
        lo + self.unit() * (hi - lo)
    }
}

// ── the φ-phase position predictor ──────────────────────────────────────

/// Map a cartesian component from `HemispherePoint::cartesian()`'s range
/// into `[0, 1)` (each component is bounded in `[-1, 1]`).
fn map01(c: f64) -> f64 {
    (c + 1.0) / 2.0
}

/// `phi_pos(n, N)` — the deterministic φ-phase position predictor: the same
/// golden-ratio hemisphere generator the sprite motion codes ride
/// (`HemispherePoint::lift(n, total).cartesian()`), mapped component-wise
/// into the unit cube.
fn phi_pos(n: usize, total: usize) -> [f64; 3] {
    let (x, z, y) = HemispherePoint::lift(n, total).cartesian();
    [map01(x), map01(z), map01(y)]
}

// ── the non-φ structured-synthetic field (surfaces + noise) ────────────

/// One random axis-aligned "surface" slab: fixed on `axis` at `plane`
/// (± noise), with independent extents on the other two axes.
#[derive(Clone, Copy, Debug)]
struct Slab {
    axis: usize,
    plane: f64,
    lo: [f64; 2],
    hi: [f64; 2],
}

/// The two axis indices other than `axis`, in ascending order.
fn other_axes(axis: usize) -> [usize; 2] {
    match axis {
        0 => [1, 2],
        1 => [0, 2],
        _ => [0, 1],
    }
}

/// Approximate a zero-mean gaussian noise sample with std `sigma`, from
/// three `unit()` draws summed and re-centered (`mean 1.5 → 0`, raw std
/// `0.5`), then rescaled to the requested `sigma`. Deterministic, no `rand`.
fn small_gauss_noise(rng: &mut SplitMix64, sigma: f64) -> f64 {
    let raw = rng.unit() + rng.unit() + rng.unit() - 1.5; // mean 0, std ≈ 0.5
    raw * (sigma / 0.5)
}

/// Build `n_slabs` random axis-aligned surface slabs.
fn build_slabs(rng: &mut SplitMix64, n_slabs: usize) -> Vec<Slab> {
    (0..n_slabs)
        .map(|_| {
            let axis = (rng.unit() * 3.0) as usize;
            let axis = axis.min(2);
            let plane = rng.range(0.1, 0.9);
            let mut lo = [0.0f64; 2];
            let mut hi = [0.0f64; 2];
            for k in 0..2 {
                let center = rng.range(0.15, 0.85);
                let half = rng.range(0.05, 0.25);
                lo[k] = (center - half).max(0.0);
                hi[k] = (center + half).min(1.0);
            }
            Slab {
                axis,
                plane,
                lo,
                hi,
            }
        })
        .collect()
}

/// Scatter `n` points near the given slabs — a structured-synthetic field
/// (surfaces + noise) that mimics real 3DGS scene structure WITHOUT ever
/// being φ-placed. Deterministic given `rng`'s starting state.
fn build_nonphi_field(rng: &mut SplitMix64, slabs: &[Slab], n: usize) -> Vec<[f64; 3]> {
    (0..n)
        .map(|_| {
            let idx = ((rng.unit() * slabs.len() as f64) as usize).min(slabs.len() - 1);
            let slab = &slabs[idx];
            let mut p = [0.0f64; 3];
            let noise = small_gauss_noise(rng, 0.02);
            p[slab.axis] = (slab.plane + noise).clamp(0.0, 0.999_999);
            for (k, &oax) in other_axes(slab.axis).iter().enumerate() {
                p[oax] = rng.range(slab.lo[k], slab.hi[k]);
            }
            p
        })
        .collect()
}

// ── Morton addressing (the honest part: address order, not oracle order) ──

/// Interleave three 6-bit axis indices (`0..64`) into an 18-bit Morton
/// (Z-order) code. Bit `k` of each axis lands at `3k + {0,1,2}` for
/// `{x,y,z}` respectively — the standard bit-interleave.
fn morton3(x: u32, y: u32, z: u32) -> u32 {
    let mut code = 0u32;
    for k in 0..6 {
        code |= ((x >> k) & 1) << (3 * k);
        code |= ((y >> k) & 1) << (3 * k + 1);
        code |= ((z >> k) & 1) << (3 * k + 2);
    }
    code
}

/// Quantize a `[0,1)`-ish coordinate to a `0..GRID` grid index.
fn quantize(c: f64) -> u32 {
    let g = (c * GRID as f64) as i64;
    g.clamp(0, (GRID - 1) as i64) as u32
}

/// The Morton-sort order: `order[rank] == original point index`.
fn morton_rank_order(points: &[[f64; 3]]) -> Vec<usize> {
    let codes: Vec<u32> = points
        .iter()
        .map(|p| morton3(quantize(p[0]), quantize(p[1]), quantize(p[2])))
        .collect();
    let mut order: Vec<usize> = (0..points.len()).collect();
    order.sort_by_key(|&i| codes[i]);
    order
}

/// Invert `morton_rank_order`'s output into a per-point rank:
/// `ranks[original_index] == its Morton rank`.
fn ranks_from_order(order: &[usize]) -> Vec<usize> {
    let mut ranks = vec![0usize; order.len()];
    for (rank, &orig_idx) in order.iter().enumerate() {
        ranks[orig_idx] = rank;
    }
    ranks
}

// ── residual / hydration measurement ────────────────────────────────────

fn euclid(a: [f64; 3], b: [f64; 3]) -> f64 {
    let dx = a[0] - b[0];
    let dy = a[1] - b[1];
    let dz = a[2] - b[2];
    (dx * dx + dy * dy + dz * dz).sqrt()
}

/// Per-point residual between the true `μ` and the φ-phase prediction at
/// its assigned rank (`phi_pos(ranks[i], total)`).
fn residuals_at_ranks(points: &[[f64; 3]], ranks: &[usize], total: usize) -> Vec<f64> {
    points
        .iter()
        .zip(ranks.iter())
        .map(|(p, &r)| euclid(*p, phi_pos(r, total)))
        .collect()
}

/// Fisher-Yates shuffle of `0..n`, deterministic via `rng`.
fn shuffled_ranks(rng: &mut SplitMix64, n: usize) -> Vec<usize> {
    let mut v: Vec<usize> = (0..n).collect();
    for i in (1..n).rev() {
        let j = ((rng.unit() * (i as f64 + 1.0)) as usize).min(i);
        v.swap(i, j);
    }
    v
}

struct HydrationStats {
    mean_res: f64,
    max_res: f64,
    rho: f64,
    escalation: f64,
}

/// The hydration core, parameterized on the ADDRESS ranks. `ranks[i]` is
/// the address assigned to point `i`; the φ-phase predictor reads
/// `phi_pos(ranks[i], total)`. `rho` is measured against a random rank
/// assignment (the chance baseline); `escalation` is the fraction of
/// points whose residual exceeds one grid cell (must be stored
/// near-losslessly). The address choice is the independent variable — the
/// whole point of leg 1 is that hydration is a property of the ADDRESS,
/// not of the data (Morton-rank vs. identity-rank give opposite verdicts
/// on the same control cloud).
fn hydration_stats_from_ranks(
    points: &[[f64; 3]],
    ranks: &[usize],
    total: usize,
    shuffle_seed: u64,
) -> HydrationStats {
    let res = residuals_at_ranks(points, ranks, total);
    let mean_res = res.iter().sum::<f64>() / points.len() as f64;
    let max_res = res.iter().cloned().fold(0.0_f64, f64::max);

    let mut rng = SplitMix64::new(shuffle_seed);
    let shuffled = shuffled_ranks(&mut rng, points.len());
    let baseline_res = residuals_at_ranks(points, &shuffled, total);
    let baseline_mean = baseline_res.iter().sum::<f64>() / points.len() as f64;

    let rho = if baseline_mean > 0.0 {
        1.0 - mean_res / baseline_mean
    } else {
        0.0
    };

    // One grid cell's euclidean extent in the unit cube: sqrt(3)/GRID.
    let threshold = 3f64.sqrt() / GRID as f64;
    let escalation = res.iter().filter(|&&r| r > threshold).count() as f64 / points.len() as f64;

    HydrationStats {
        mean_res,
        max_res,
        rho,
        escalation,
    }
}

/// The hydration measurement at the natural SPATIAL address: the
/// Morton-rank order over quantized `μ`. This is the address a *static*
/// cloud actually has (no sequential generation index).
fn hydration_stats(points: &[[f64; 3]], total: usize, shuffle_seed: u64) -> HydrationStats {
    let order = morton_rank_order(points);
    let ranks = ranks_from_order(&order);
    hydration_stats_from_ranks(points, &ranks, total, shuffle_seed)
}

// ── comma anti-moiré fence (orthogonal to hydration) ────────────────────

/// Steinhaus three-gap (three-distance) theorem: for any irrational α, the
/// sorted fractional parts `{n·α}` for `n ∈ 0..N` partition the circle into
/// arcs taking **at most 3 distinct lengths**. This is the correct
/// aperiodicity / low-discrepancy signature of the golden rotation — the
/// discrete Pythagorean-comma structure. (Lag-autocorrelation is the WRONG
/// tool: `{n·φ}` is a deterministic equidistributed rotation, not a
/// stationary stochastic process, so Pearson autocorr mis-measures it — a
/// large lag-1 autocorr there reflects the near-constant golden STEP, not
/// periodicity.) Returns the distinct-gap count; `≤ 3` is the theorem's
/// guarantee and the aperiodicity certificate.
fn three_gap_distinct_count(seq: &[f64]) -> usize {
    let mut s: Vec<f64> = seq.to_vec();
    s.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let n = s.len();
    if n < 2 {
        return 0;
    }
    // Circular gaps: consecutive differences, wrapping the last back to the
    // first (+1.0, one full turn).
    let gaps: Vec<f64> = (0..n)
        .map(|i| {
            let next = if i + 1 < n { s[i + 1] } else { s[0] + 1.0 };
            next - s[i]
        })
        .collect();
    // Gap classes differ by ~1/N ≈ 2.4e-4 at N=4096; f64 fract error is
    // ~1e-12, so 1e-9 cleanly separates the classes without merging them.
    let tol = 1e-9;
    let mut distinct: Vec<f64> = Vec::new();
    for &g in &gaps {
        if !distinct.iter().any(|&d| (d - g).abs() < tol) {
            distinct.push(g);
        }
    }
    distinct.len()
}

/// The stride-4-over-17 coprime walk `w[k] = (4*k) mod 17`. `gcd(4,17)=1`
/// so it must visit all 17 residues exactly once (a full permutation) —
/// the discrete comma / anti-moiré device.
fn coprime_walk_is_full_permutation() -> bool {
    let mut seen = [false; 17];
    for k in 0..17u32 {
        let w = (4 * k % 17) as usize;
        if seen[w] {
            return false;
        }
        seen[w] = true;
    }
    seen.iter().all(|&s| s)
}

fn main() {
    // CONTROL: μ literally generated by the φ-hemisphere lift.
    let mu_ctrl: Vec<[f64; 3]> = (0..N).map(|n| phi_pos(n, N)).collect();

    // NON-φ: structured-synthetic surfaces-plus-noise field, never φ-placed.
    let mut rng = SplitMix64::new(SEED);
    let slabs = build_slabs(&mut rng, 8);
    let mu_nonphi = build_nonphi_field(&mut rng, &slabs, N);

    let sets: [(&str, &[[f64; 3]], u64); 2] = [
        ("ctrl", mu_ctrl.as_slice(), SEED ^ 0x0C71_0000_0000_0001),
        ("nonphi", mu_nonphi.as_slice(), SEED ^ 0x0C71_0000_0000_0002),
    ];
    for (label, points, shuffle_seed) in sets {
        let stats = hydration_stats(points, N, shuffle_seed);
        eprintln!(
            "MUHYD set={label} mean_res={:.4} max_res={:.4} rho={:.4} escalation={:.4}",
            stats.mean_res, stats.max_res, stats.rho, stats.escalation
        );
    }

    // CONTROL by GENERATION-index address (identity ranks 0..N). The φ-phase
    // hydrates the control cloud PERFECTLY here (rho → 1, residual → 0)
    // because `mu_ctrl[n] == phi_pos(n, N)` by construction. Contrast with
    // `set=ctrl` above (Morton-rank ≈ 0): SAME data, opposite verdict. This
    // isolates the mechanism — hydration is a property of the ADDRESS, not
    // of the data. The static-cloud DROP is precisely the absence of the
    // generation index: the space-filling φ-spiral (the comma) scatters `n`
    // across the grid, so a spatial (Morton) address cannot recover it.
    // Motion HAS this index (the path/frame counter) — hence μ-hydration ⊂
    // motion-hydration.
    let identity_ranks: Vec<usize> = (0..N).collect();
    let stats_naddr =
        hydration_stats_from_ranks(&mu_ctrl, &identity_ranks, N, SEED ^ 0x0C71_0000_0000_0003);
    eprintln!(
        "MUHYD set=ctrl_naddr mean_res={:.4} max_res={:.4} rho={:.4} escalation={:.4}",
        stats_naddr.mean_res, stats_naddr.max_res, stats_naddr.rho, stats_naddr.escalation
    );

    // Comma fence, leg A — golden-rotation aperiodicity via the Steinhaus
    // three-gap theorem: the sorted fractional parts {n·φ} take ≤ 3 distinct
    // arc lengths. This is the correct low-discrepancy / anti-moiré
    // certificate for the deterministic phase (replaces a mis-specified
    // lag-autocorrelation of the same sequence).
    let phi = (1.0 + 5.0_f64.sqrt()) / 2.0;
    let phi_seq: Vec<f64> = (0..N)
        .map(|n| {
            let v = n as f64 * phi;
            v - v.floor()
        })
        .collect();
    let three_gap = three_gap_distinct_count(&phi_seq);
    eprintln!("MUHYD comma_phi_three_gap_distinct={three_gap}");

    // Comma fence, leg B — the discrete coprime-walk full permutation.
    let full_perm = coprime_walk_is_full_permutation();
    eprintln!(
        "MUHYD comma_coprime_full_perm={}",
        if full_perm { 1 } else { 0 }
    );

    eprintln!("MUHYD N={N} grid={GRID}");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// (1) The non-φ field build is deterministic: two builds from the same
    /// seed produce byte-identical slabs and points.
    #[test]
    fn nonphi_field_build_is_deterministic() {
        let mut rng1 = SplitMix64::new(SEED);
        let slabs1 = build_slabs(&mut rng1, 8);
        let field1 = build_nonphi_field(&mut rng1, &slabs1, 256);

        let mut rng2 = SplitMix64::new(SEED);
        let slabs2 = build_slabs(&mut rng2, 8);
        let field2 = build_nonphi_field(&mut rng2, &slabs2, 256);

        assert_eq!(field1.len(), field2.len());
        for (a, b) in field1.iter().zip(field2.iter()) {
            assert_eq!(a, b, "non-φ field build must be deterministic");
        }
    }

    /// (2) The core contract: the CONTROL set (μ literally φ-generated)
    /// must hydrate strictly better than the NON-φ structured-synthetic
    /// field, i.e. `rho_ctrl > rho_nonphi`. This is the falsifiable claim
    /// `E-3DGS-MU-HYDRATION-1` leg 1 exists to check.
    #[test]
    fn control_hydrates_better_than_nonphi() {
        let n = 512;
        let mu_ctrl: Vec<[f64; 3]> = (0..n).map(|k| phi_pos(k, n)).collect();

        let mut rng = SplitMix64::new(SEED);
        let slabs = build_slabs(&mut rng, 8);
        let mu_nonphi = build_nonphi_field(&mut rng, &slabs, n);

        let stats_ctrl = hydration_stats(&mu_ctrl, n, SEED ^ 0xC0);
        let stats_nonphi = hydration_stats(&mu_nonphi, n, SEED ^ 0xC1);

        assert!(
            stats_ctrl.rho > stats_nonphi.rho,
            "control rho {} should exceed non-φ rho {}",
            stats_ctrl.rho,
            stats_nonphi.rho
        );
    }

    /// (3) The discrete comma: `gcd(4,17)=1` guarantees the stride-4 walk
    /// visits all 17 residues exactly once.
    #[test]
    fn coprime_walk_visits_all_residues_exactly_once() {
        assert!(coprime_walk_is_full_permutation());
    }

    /// (4) The continuous comma: the Steinhaus three-gap theorem bounds the
    /// golden rotation `{n·φ}` to `≤ 3` distinct sorted-arc lengths. This is
    /// the aperiodicity certificate that replaces the mis-specified
    /// lag-autocorrelation metric.
    #[test]
    fn golden_rotation_has_at_most_three_gaps() {
        let phi = (1.0 + 5.0_f64.sqrt()) / 2.0;
        for &n in &[16usize, 256, 512, 4096] {
            let seq: Vec<f64> = (0..n)
                .map(|k| {
                    let v = k as f64 * phi;
                    v - v.floor()
                })
                .collect();
            let gaps = three_gap_distinct_count(&seq);
            assert!(
                gaps <= 3,
                "three-gap theorem violated at N={n}: {gaps} distinct gaps"
            );
        }
    }

    /// (5) The addressing-isolation contract: the CONTROL cloud hydrates
    /// PERFECTLY at its generation-index address (identity ranks) — same
    /// data, opposite verdict from the Morton-rank address. Proves hydration
    /// is a property of the ADDRESS, not the data.
    #[test]
    fn control_hydrates_perfectly_at_generation_index() {
        let n = 512;
        let mu_ctrl: Vec<[f64; 3]> = (0..n).map(|k| phi_pos(k, n)).collect();
        let identity_ranks: Vec<usize> = (0..n).collect();
        let stats = hydration_stats_from_ranks(&mu_ctrl, &identity_ranks, n, SEED ^ 0xC2);
        assert!(
            stats.mean_res < 1e-12,
            "generation-index residual must be ~0, got {}",
            stats.mean_res
        );
        assert!(
            stats.rho > 0.999,
            "generation-index rho must be ~1, got {}",
            stats.rho
        );
    }
}
