//! `causal_knowledge_transfer` — understand the MEANING of a fable (Aesop's
//! scorpion & frog) as a **causality trajectory**, then TRANSFER that meaning to
//! a SEPARATE story with different people — *without re-deriving it*. The moral,
//! AND its felt **qualia**, are properties of the trajectory SIGNATURE, not the
//! entities; any story whose causal structure matches inherits both (NARS analogy
//! over the shared abstract trajectory — the `E-REASONING-CORE-GROUND-TRUTH-1`
//! cross-text-transfer claim, made runnable).
//!
//! The causality trajectory (Pearl-rung-decomposed — W-B):
//! ```text
//!   agent --has--> NATURE --compels--> ACT --causes--> HARM
//!   Rung 1 (SO)  association:   agent ~ harm
//!   Rung 2 (PO)  intervention:  do(agent, ACT := nothing) → no harm   ⟹ AVOIDABLE
//!   Rung 3 (SPO) counterfactual: NATURE ⊨ ACT ⇒ do(¬ACT) unreachable  ⟹ NECESSARY
//!   moral = AVOIDABLE ∧ NECESSARY  (a preserved contradiction, not a scalar)
//! ```
//! and its **qualia** = the felt magnitude of holding both poles: high `tension`
//! (both truths kept), high `depth` (modal necessity), tragic `valence`, and the
//! derived `wonder = √(coherence·expansion)`. In production the trajectory is
//! generated by the 2³ rung fan (W-B), dispatched by the 34-recipe/MUL loop (W-D),
//! and driven by the kanban step-strategies; here it is composed directly.
//!
//! ```sh
//! cargo run -p lance-graph --example causal_knowledge_transfer
//! ```

use lance_graph::graph::arigraph::triplet_graph::{Triplet, TripletGraph};
use lance_graph_contract::qualia::{QualiaI4_16D, QUALIA_I4_LABELS};

/// The transferable unit: the relation signature of a causality trajectory.
/// `agent --has--> nature --compels--> act --causes--> harm`. Two stories with
/// the same signature share the same meaning, regardless of their entities.
#[derive(Clone, Copy)]
struct Trajectory {
    has: &'static str,
    compels: &'static str,
    causes: &'static str,
}

/// The MEANING of a trajectory: the Pearl-rung moral + its felt qualia.
#[derive(Clone, Copy)]
struct Meaning {
    avoidable: bool,      // Rung 2: do(¬act) removes the harm
    necessary: bool,      // Rung 3: nature ⊨ act ⇒ do(¬act) unreachable
    qualia: QualiaI4_16D, // the felt magnitude of the preserved contradiction
}

/// One story's causal chain (SPO; `Triplet::new` is `(subject, OBJECT, relation, ts)`).
fn story(agent: &str, nature: &str, act: &str, harm: &str, victim: &str) -> Vec<Triplet> {
    vec![
        Triplet::new(agent, nature, "has", 1),   // agent has nature
        Triplet::new(nature, act, "compels", 2), // nature compels act
        Triplet::new(act, harm, "causes", 3),    // act causes harm
        Triplet::new(agent, victim, act, 4),     // agent <act>s victim (the deed)
    ]
}

/// The felt magnitude of a moral, wired onto the canonical qualia lanes. A
/// preserved contradiction (avoidable ∧ necessary) is maximally tense, deep,
/// tragic, and full of wonder; a resolved/scalar outcome is flat.
fn qualia_of(avoidable: bool, necessary: bool) -> QualiaI4_16D {
    let mut q = QualiaI4_16D(0);
    if avoidable && necessary {
        q.set(2, 7); // tension:   both poles held at once
        q.set(6, 6); // depth:     the modal necessity beneath the deed
        q.set(1, -5); // valence:  tragic (the harm is real)
        q.set(9, 4); // coherence: the trajectory hangs together
        q.set(15, 4); // expansion: the moral generalizes beyond this story
    } else if avoidable {
        q.set(1, 3); // merely avoidable → relief, not tragedy
    }
    q
}

/// `wonder` (Staunen) — the derived awe of a moral: `√(coherence · expansion)`
/// (qualia.rs axis note). High only when the trajectory is both coherent and
/// generalizing — i.e. a real transferable meaning.
fn wonder(q: QualiaI4_16D) -> f32 {
    let coherence = q.get(9).max(0) as f32;
    let expansion = q.get(15).max(0) as f32;
    (coherence * expansion).sqrt()
}

/// UNDERSTAND a story: extract its trajectory + compute the meaning. `avoidable`
/// via the shipped `intervene_on` do-operator (Rung 2, non-mutating); `necessary`
/// via the modal chain (Rung 3); the qualia via `qualia_of`.
fn understand(
    agent: &str,
    nature: &str,
    act: &str,
    harm: &str,
    victim: &str,
) -> (Trajectory, Meaning) {
    let mut g = TripletGraph::new();
    g.add_triplets(&story(agent, nature, act, harm, victim));

    // Rung 2 — the road not taken: do(agent, act := nothing). Non-mutating.
    let cfact = g.intervene_on(agent, act, "nothing");
    // Avoidable iff the deed is a single causal antecedent of the harm that the
    // do-operator can lift (the counterfactual replaces it without touching the graph).
    let avoidable = cfact.triplet.object == "nothing"
        && g.triplets
            .iter()
            .any(|t| t.subject == act && t.relation == "causes" && t.object == harm);

    // Rung 3 — necessity: nature compels the act, so do(¬act) is unreachable.
    let necessary = g
        .triplets
        .iter()
        .any(|t| t.subject == agent && t.relation == "has" && t.object == nature)
        && g.triplets
            .iter()
            .any(|t| t.subject == nature && t.relation == "compels" && t.object == act);

    let qualia = qualia_of(avoidable, necessary);
    (
        Trajectory {
            has: "has",
            compels: "compels",
            causes: "causes",
        },
        Meaning {
            avoidable,
            necessary,
            qualia,
        },
    )
}

/// TRANSFER: does a *new* story match the learned trajectory signature? If so it
/// INHERITS the meaning (moral + qualia) — no counterfactual is re-run. This is
/// the knowledge transfer: the fable's understanding applied to other people.
fn transfer(
    traj: &Trajectory,
    learned: &Meaning,
    agent: &str,
    nature: &str,
    act: &str,
    harm: &str,
    victim: &str,
) -> Option<Meaning> {
    let mut g = TripletGraph::new();
    g.add_triplets(&story(agent, nature, act, harm, victim));
    let has = |s: &str, r: &str, o: &str| {
        g.triplets
            .iter()
            .any(|t| t.subject == s && t.relation == r && t.object == o)
    };
    let matches = has(agent, traj.has, nature)
        && has(nature, traj.compels, act)
        && has(act, traj.causes, harm);
    matches.then_some(*learned) // the SAME meaning + qualia, inherited by structure
}

fn qualia_line(q: QualiaI4_16D) -> String {
    (0..16)
        .filter(|&d| q.get(d) != 0)
        .map(|d| format!("{}={:+}", QUALIA_I4_LABELS[d], q.get(d)))
        .collect::<Vec<_>>()
        .join(" ")
}

fn main() {
    println!("── causal_knowledge_transfer : one fable, transferred to a separate story ──\n");

    // ── STORY A: understand the fable's meaning. ──
    let (traj, meaning_a) = understand("scorpion", "nature", "stings", "death", "frog");
    println!("STORY A (the fable): scorpion --has--> nature --compels--> stings --causes--> death");
    println!(
        "  meaning: avoidable={} ∧ necessary={}  ⇒ moral = the death is BOTH (the preserved contradiction)",
        meaning_a.avoidable, meaning_a.necessary
    );
    println!(
        "  qualia : {}   wonder(Staunen)={:.2}",
        qualia_line(meaning_a.qualia),
        wonder(meaning_a.qualia)
    );
    println!(
        "  trajectory signature learned: X --{}--> N --{}--> A --{}--> H\n",
        traj.has, traj.compels, traj.causes
    );

    // ── STORY B: a SEPARATE story, different people. Transfer, don't re-derive. ──
    println!("STORY B (separate, new people): marcus --has--> ambition --compels--> betrays --causes--> ruin");
    match transfer(
        &traj, &meaning_a, "marcus", "ambition", "betrays", "ruin", "elena",
    ) {
        Some(m) => {
            println!(
                "  ✔ trajectory signature MATCHES → meaning INHERITED (no counterfactual re-run):"
            );
            println!(
                "  meaning: avoidable={} ∧ necessary={}  ⇒ Marcus's betrayal of Elena is BOTH — the SAME moral",
                m.avoidable, m.necessary
            );
            println!(
                "  qualia : {}   wonder(Staunen)={:.2}  (the felt tragedy transfers too)",
                qualia_line(m.qualia),
                wonder(m.qualia)
            );
        }
        None => println!("  ✘ signature did not match — no transfer"),
    }

    // ── A story that does NOT match: no transfer (the meaning is structural). ──
    println!("\nSTORY C (no compulsion): a merchant --sells--> cloth --to--> a buyer");
    let mut gc = TripletGraph::new();
    gc.add_triplets(&[Triplet::new("merchant", "cloth", "sells", 1)]);
    let c_has_traj = gc.triplets.iter().any(|t| t.relation == traj.compels);
    println!(
        "  {} — no `compels` edge → no causality trajectory → the fable's moral does NOT transfer.",
        if c_has_traj {
            "matches?!"
        } else {
            "signature ABSENT"
        }
    );

    println!("\n── the point (endgame: reason-about-itself + knowledge transfer, no LLM) ──");
    println!("The fable's MEANING is not about scorpions — it is the causality trajectory");
    println!("(has→compels→causes) and its Pearl rungs (avoidable ∧ necessary). Because the");
    println!("meaning lives in the SIGNATURE, understanding one story transfers to any story");
    println!("that shares it — Marcus inherits the scorpion's moral AND its felt qualia without");
    println!("re-deriving a single counterfactual. That is knowledge transfer over causality");
    println!("trajectories; W-B generates the rungs, W-D's recipes do the analogy, the kanban");
    println!("step-strategies drive the cycle, and the QualiaI4_16D carries the felt magnitude.");
}
