// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The Lance Authors

//! Bucket-dispatch Op emitter — **Phase 2** of the Odoo SoA → Foundry SoC
//! pipeline.
//!
//! # Pipeline position
//!
//! ```text
//!   Typed Odoo SoA  (OdooEntity[])
//!        │  style_recipe::derive_style_recipe (Phase 1, PR #433)
//!        ▼
//!   OdooStyleRecipe[]   (DAtom weights + regulatory anchors)
//!        │  THIS MODULE — bucket_corpus + emit_op_dispatch (Phase 2)
//!        ▼
//!   Rust source String  (RECIPE_* consts + per-kind Op structs + static slices)
//!        │  write via build.rs → OUT_DIR → include!()
//!        ▼
//!   Compiled SoC dispatch table  (O(1) recipe lookup at runtime)
//! ```
//!
//! # Conceptual split
//!
//! `derive_style_recipe` (Phase 1) asks: **what does this method DO** — give
//! it a sparse DAtom weight vector.
//!
//! `bucket_corpus` (Phase 2) asks: **what KIND of method is it** — put it in
//! the right dispatch bucket by `OdooMethodKind` semantic role.
//!
//! `emit_op_dispatch` (Phase 2) asks: **what does the compiler need** — emit
//! a deterministic Rust source file the SoC synergy stage compiles into
//! O(1) dispatch tables.
//!
//! # Emitted structure (per bucket that has ≥1 method)
//!
//! ```rust,ignore
//! // --- auto-generated by odoo_blueprint::op_emitter ---
//!
//! // ─── Recipe collapse keys ──────────────────────────────────────────────
//! /// entity=1 compute=4
//! pub const RECIPE_A1B2C3D4: u32 = 0xA1B2C3D4;
//! // ...
//!
//! // ─── Compute bucket (N methods) ────────────────────────────────────────
//! #[derive(Debug, Clone, Copy)]
//! pub struct ComputeOp {
//!     pub method_id: &'static str,
//!     pub recipe_id: u32,
//! }
//! pub static COMPUTE_OPS: &[ComputeOp] = &[
//!     ComputeOp { method_id: "account.move._compute_amount", recipe_id: 0xA1B2C3D4 },
//! ];
//! ```
//!
//! # Determinism guarantees
//!
//! - `RECIPE_*` consts are emitted in ascending `recipe_id` order.
//! - Buckets are emitted in `OdooMethodKind` declaration order.
//! - Within each bucket, `Op` entries are sorted by `recipe_id` then `method_id`.
//!
//! # Zero-dep output
//!
//! The emitted file uses only primitive Rust types (`u32`, `&'static str`).
//! Consumers `include!` it from `OUT_DIR`; no imports needed in the output.

use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;

use crate::odoo_blueprint::style_recipe::{derive_style_recipe, OdooStyleRecipe};
use crate::odoo_blueprint::{OdooEntity, OdooMethodKind};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// One bucketed recipe: method identity + semantic kind + DAtom fingerprint.
///
/// Produced by [`bucket_corpus`] — the bridge between the interpretation step
/// (Phase 1) and the codegen step (Phase 2).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BucketedRecipe {
    /// Fully-qualified method id: `"account.move._compute_amount"`.
    pub method_id: String,
    /// Semantic role dispatch bucket — drives Op struct selection.
    pub kind: OdooMethodKind,
    /// DAtom fingerprint + regulatory anchors (the Phase 1 output).
    pub recipe: OdooStyleRecipe,
}

/// Emit statistics produced alongside the Rust source.
#[derive(Debug, Clone)]
pub struct EmitStats {
    /// Total methods processed (one entry per entity×method pair).
    pub total_methods: usize,
    /// Count of unique `recipe_id` values (the collapse count).
    pub unique_recipes: usize,
    /// Per-kind method counts, in `OdooMethodKind` declaration order.
    pub kind_counts: Vec<(OdooMethodKind, usize)>,
}

// ---------------------------------------------------------------------------
// Public functions
// ---------------------------------------------------------------------------

/// Walk every entity's methods, derive their DAtom recipe, and pair each
/// with its semantic method kind.
///
/// Empty entities (no methods) and empty entity slices both produce `vec![]`.
/// All 10 `OdooMethodKind` variants are eligible — including `Helper` and
/// `Override`, whose recipes carry only the `Entity=1` anchor.
pub fn bucket_corpus(entities: &[&OdooEntity]) -> Vec<BucketedRecipe> {
    let mut out = Vec::new();
    for entity in entities {
        for method in entity.methods {
            let recipe = derive_style_recipe(entity, method);
            out.push(BucketedRecipe {
                method_id: recipe.method_id.clone(),
                kind: method.kind,
                recipe,
            });
        }
    }
    out
}

/// Emit the compilable Rust Op dispatch source from a bucketed recipe corpus.
///
/// Returns the source `String` and [`EmitStats`]. Write the source to a file
/// in `OUT_DIR` (e.g. via `build.rs`) and `include!` it in the consumer.
///
/// Calling with an empty `buckets` slice produces a valid Rust file (just
/// the header comments — no structs, no statics). This is intentional: an
/// empty corpus is a valid (though probably misconfigured) input.
pub fn emit_op_dispatch(buckets: &[BucketedRecipe]) -> (String, EmitStats) {
    // Collect unique recipes (BTreeMap gives ascending recipe_id order).
    let mut recipe_map: BTreeMap<u32, &OdooStyleRecipe> = BTreeMap::new();
    for b in buckets {
        recipe_map.entry(b.recipe.recipe_id).or_insert(&b.recipe);
    }

    // Group buckets by kind in declaration order.
    let groups = group_by_kind(buckets);

    // Build kind_counts for stats.
    let kind_counts: Vec<(OdooMethodKind, usize)> =
        groups.iter().map(|(k, v)| (*k, v.len())).collect();

    let mut src = String::new();

    // Header
    writeln!(
        src,
        "// --- auto-generated by odoo_blueprint::op_emitter ---"
    )
    .unwrap();
    writeln!(
        src,
        "// DO NOT EDIT: regenerate via `bucket_corpus` + `emit_op_dispatch`"
    )
    .unwrap();
    writeln!(src, "//").unwrap();
    writeln!(src, "// Buckets : {}", groups.len()).unwrap();
    writeln!(src, "// Unique recipes : {}", recipe_map.len()).unwrap();
    writeln!(src, "// Total methods  : {}", buckets.len()).unwrap();
    writeln!(src).unwrap();

    // 1. Recipe collapse-key consts
    if !recipe_map.is_empty() {
        writeln!(
            src,
            "// ─── Recipe collapse keys \
             ────────────────────────────────────────────────────"
        )
        .unwrap();
        for (id, recipe) in &recipe_map {
            let comment = atom_comment(recipe);
            writeln!(src, "/// {comment}").unwrap();
            writeln!(src, "pub const RECIPE_{id:08X}: u32 = 0x{id:08X};").unwrap();
        }
        writeln!(src).unwrap();
    }

    // 2. Per-kind Op struct + static slice
    for (kind, entries) in &groups {
        let pascal = kind_pascal(*kind);
        let upper = kind_upper(*kind);
        let count = entries.len();

        // Sort for determinism: recipe_id asc, then method_id asc.
        let mut sorted: Vec<&BucketedRecipe> = entries.iter().copied().collect();
        sorted.sort_by(|a, b| {
            a.recipe
                .recipe_id
                .cmp(&b.recipe.recipe_id)
                .then_with(|| a.method_id.cmp(&b.method_id))
        });

        writeln!(
            src,
            "// ─── {pascal} bucket ({count} {}) \
             ─────────────────────────────────────────────────",
            if count == 1 { "method" } else { "methods" }
        )
        .unwrap();
        writeln!(src, "/// An Op in the `{pascal}` dispatch bucket.").unwrap();
        writeln!(src, "#[derive(Debug, Clone, Copy)]").unwrap();
        writeln!(src, "pub struct {pascal}Op {{").unwrap();
        writeln!(src, "    pub method_id: &'static str,").unwrap();
        writeln!(src, "    pub recipe_id: u32,").unwrap();
        writeln!(src, "}}").unwrap();
        writeln!(src).unwrap();
        writeln!(
            src,
            "/// All `{pascal}` Ops, sorted by `recipe_id` then `method_id`."
        )
        .unwrap();
        writeln!(src, "pub static {upper}_OPS: &[{pascal}Op] = &[").unwrap();
        for e in &sorted {
            writeln!(
                src,
                "    {pascal}Op {{ method_id: {:?}, recipe_id: 0x{:08X} }},",
                e.method_id, e.recipe.recipe_id
            )
            .unwrap();
        }
        writeln!(src, "];").unwrap();
        writeln!(src).unwrap();
    }

    let stats = EmitStats {
        total_methods: buckets.len(),
        unique_recipes: recipe_map.len(),
        kind_counts,
    };

    (src, stats)
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/// Group `BucketedRecipe` slices by kind, in `OdooMethodKind` declaration
/// order. Kinds with no entries are omitted.
fn group_by_kind(buckets: &[BucketedRecipe]) -> Vec<(OdooMethodKind, Vec<&BucketedRecipe>)> {
    // Accumulate into a BTreeMap keyed by declaration-order index.
    let mut map: BTreeMap<u8, Vec<&BucketedRecipe>> = BTreeMap::new();
    for b in buckets {
        map.entry(kind_ord(b.kind)).or_default().push(b);
    }
    map.into_iter()
        .map(|(ord, v)| (kind_from_ord(ord), v))
        .collect()
}

/// Stable ordinal matching `OdooMethodKind` declaration order.
const fn kind_ord(k: OdooMethodKind) -> u8 {
    match k {
        OdooMethodKind::Compute => 0,
        OdooMethodKind::Inverse => 1,
        OdooMethodKind::Constrain => 2,
        OdooMethodKind::Onchange => 3,
        OdooMethodKind::Action => 4,
        OdooMethodKind::Cron => 5,
        OdooMethodKind::ApiModel => 6,
        OdooMethodKind::ApiModelCreateMulti => 7,
        OdooMethodKind::Override => 8,
        OdooMethodKind::Helper => 9,
    }
}

fn kind_from_ord(ord: u8) -> OdooMethodKind {
    match ord {
        0 => OdooMethodKind::Compute,
        1 => OdooMethodKind::Inverse,
        2 => OdooMethodKind::Constrain,
        3 => OdooMethodKind::Onchange,
        4 => OdooMethodKind::Action,
        5 => OdooMethodKind::Cron,
        6 => OdooMethodKind::ApiModel,
        7 => OdooMethodKind::ApiModelCreateMulti,
        8 => OdooMethodKind::Override,
        9 => OdooMethodKind::Helper,
        _ => unreachable!("kind_ord range is 0..=9"),
    }
}

/// PascalCase name for the emitted Op struct (e.g. `Compute`, `ApiModel`).
const fn kind_pascal(k: OdooMethodKind) -> &'static str {
    match k {
        OdooMethodKind::Compute => "Compute",
        OdooMethodKind::Inverse => "Inverse",
        OdooMethodKind::Constrain => "Constrain",
        OdooMethodKind::Onchange => "Onchange",
        OdooMethodKind::Action => "Action",
        OdooMethodKind::Cron => "Cron",
        OdooMethodKind::ApiModel => "ApiModel",
        OdooMethodKind::ApiModelCreateMulti => "ApiModelCreateMulti",
        OdooMethodKind::Override => "Override",
        OdooMethodKind::Helper => "Helper",
    }
}

/// UPPER_SNAKE name for the emitted static slice (e.g. `COMPUTE`, `API_MODEL`).
const fn kind_upper(k: OdooMethodKind) -> &'static str {
    match k {
        OdooMethodKind::Compute => "COMPUTE",
        OdooMethodKind::Inverse => "INVERSE",
        OdooMethodKind::Constrain => "CONSTRAIN",
        OdooMethodKind::Onchange => "ONCHANGE",
        OdooMethodKind::Action => "ACTION",
        OdooMethodKind::Cron => "CRON",
        OdooMethodKind::ApiModel => "API_MODEL",
        OdooMethodKind::ApiModelCreateMulti => "API_MODEL_CREATE_MULTI",
        OdooMethodKind::Override => "OVERRIDE",
        OdooMethodKind::Helper => "HELPER",
    }
}

/// Human-readable doc-comment line summarising a recipe's atom weights.
///
/// Example: `"entity=1 compute=4 law=8"`.
fn atom_comment(recipe: &OdooStyleRecipe) -> String {
    if recipe.atoms.is_empty() {
        return "empty".to_owned();
    }
    recipe
        .atoms
        .iter()
        .map(|(a, w)| format!("{}={}", a.id(), w))
        .collect::<Vec<_>>()
        .join(" ")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::odoo_blueprint::style_recipe::DAtom;
    use crate::odoo_blueprint::{
        OdooConfidence, OdooEntity, OdooEntityKind, OdooField, OdooFieldKind, OdooMethod,
        OdooMethodKind, OdooProvenance, OdooReturnKind, OdooSemanticRole,
    };

    // ── Minimal fixture ──────────────────────────────────────────────────────

    const EMPTY_PROVENANCE: OdooProvenance = OdooProvenance {
        l_doc: "test.md",
        l_doc_lines: (1, 1),
        odoo_source: &[],
        confidence: OdooConfidence::Conjecture,
        regulation_iri: &[],
    };

    const COMPUTE_METHOD: OdooMethod = OdooMethod {
        name: "_compute_amount",
        kind: OdooMethodKind::Compute,
        return_kind: OdooReturnKind::Unit,
        triggers: &[],
    };

    const ACTION_METHOD: OdooMethod = OdooMethod {
        name: "action_post",
        kind: OdooMethodKind::Action,
        return_kind: OdooReturnKind::Action,
        triggers: &["posted"],
    };

    const CONSTRAIN_METHOD: OdooMethod = OdooMethod {
        name: "_check_date",
        kind: OdooMethodKind::Constrain,
        return_kind: OdooReturnKind::Unit,
        triggers: &[],
    };

    const TEST_ENTITY: OdooEntity = OdooEntity {
        model_name: "test.move",
        kind: OdooEntityKind::Model,
        description: "Test entity",
        fields: &[OdooField {
            name: "amount",
            kind: OdooFieldKind::Monetary,
            target: None,
            required: false,
            computed: Some("_compute_amount"),
            depends: &[],
            semantic_role: OdooSemanticRole::Money,
        }],
        methods: &[COMPUTE_METHOD, ACTION_METHOD, CONSTRAIN_METHOD],
        decorators: &[],
        state_machine: None,
        constraints: &[],
        provenance: EMPTY_PROVENANCE,
    };

    const HELPER_ENTITY: OdooEntity = OdooEntity {
        model_name: "test.helper",
        kind: OdooEntityKind::Model,
        description: "Entity with a helper method",
        fields: &[],
        methods: &[OdooMethod {
            name: "_prepare_vals",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        }],
        decorators: &[],
        state_machine: None,
        constraints: &[],
        provenance: EMPTY_PROVENANCE,
    };

    // ── Tests ────────────────────────────────────────────────────────────────

    #[test]
    fn bucket_corpus_empty_input_produces_empty_vec() {
        let result = bucket_corpus(&[]);
        assert!(result.is_empty());
    }

    #[test]
    fn bucket_corpus_no_methods_entity_produces_empty_vec() {
        const NO_METHODS: OdooEntity = OdooEntity {
            model_name: "test.empty",
            kind: OdooEntityKind::Model,
            description: "No methods",
            fields: &[],
            methods: &[],
            decorators: &[],
            state_machine: None,
            constraints: &[],
            provenance: EMPTY_PROVENANCE,
        };
        let result = bucket_corpus(&[&NO_METHODS]);
        assert!(result.is_empty());
    }

    #[test]
    fn bucket_corpus_groups_three_methods_into_correct_kinds() {
        let buckets = bucket_corpus(&[&TEST_ENTITY]);
        assert_eq!(buckets.len(), 3, "three methods → three buckets");

        let kinds: Vec<OdooMethodKind> = buckets.iter().map(|b| b.kind).collect();
        assert!(kinds.contains(&OdooMethodKind::Compute));
        assert!(kinds.contains(&OdooMethodKind::Action));
        assert!(kinds.contains(&OdooMethodKind::Constrain));
    }

    #[test]
    fn bucket_corpus_method_id_matches_entity_dot_method() {
        let buckets = bucket_corpus(&[&TEST_ENTITY]);
        let compute = buckets
            .iter()
            .find(|b| b.kind == OdooMethodKind::Compute)
            .unwrap();
        assert_eq!(compute.method_id, "test.move._compute_amount");
    }

    #[test]
    fn emit_op_dispatch_empty_produces_valid_header_only_rust() {
        let (src, stats) = emit_op_dispatch(&[]);
        // Header must be present
        assert!(src.contains("auto-generated by odoo_blueprint::op_emitter"));
        // No structs emitted for empty input
        assert!(!src.contains("pub struct"));
        assert!(!src.contains("pub static"));
        assert_eq!(stats.total_methods, 0);
        assert_eq!(stats.unique_recipes, 0);
        assert!(stats.kind_counts.is_empty());
    }

    #[test]
    fn emit_op_dispatch_produces_struct_and_static_for_each_kind() {
        let buckets = bucket_corpus(&[&TEST_ENTITY]);
        let (src, stats) = emit_op_dispatch(&buckets);

        // Three kinds present → three structs + three statics
        assert!(src.contains("pub struct ComputeOp {"), "ComputeOp struct");
        assert!(
            src.contains("pub static COMPUTE_OPS:"),
            "COMPUTE_OPS static"
        );
        assert!(src.contains("pub struct ActionOp {"), "ActionOp struct");
        assert!(src.contains("pub static ACTION_OPS:"), "ACTION_OPS static");
        assert!(
            src.contains("pub struct ConstrainOp {"),
            "ConstrainOp struct"
        );
        assert!(
            src.contains("pub static CONSTRAIN_OPS:"),
            "CONSTRAIN_OPS static"
        );

        // Helper / Override / Onchange / etc. absent (not in TEST_ENTITY)
        assert!(!src.contains("pub struct HelperOp"), "no HelperOp");
        assert!(!src.contains("pub struct OnchangeOp"), "no OnchangeOp");

        assert_eq!(stats.total_methods, 3);
        assert_eq!(stats.kind_counts.len(), 3);
    }

    #[test]
    fn emit_op_dispatch_recipe_const_present_for_each_unique_id() {
        let buckets = bucket_corpus(&[&TEST_ENTITY]);
        let (src, stats) = emit_op_dispatch(&buckets);

        // Each unique recipe_id must appear as a RECIPE_* const
        for b in &buckets {
            let const_name = format!("RECIPE_{:08X}", b.recipe.recipe_id);
            assert!(
                src.contains(&const_name),
                "missing const {const_name} in emitted source"
            );
        }
        // unique_recipes ≤ total_methods (dedup possible)
        assert!(stats.unique_recipes <= stats.total_methods);
    }

    #[test]
    fn emit_op_dispatch_deterministic_across_calls() {
        let buckets = bucket_corpus(&[&TEST_ENTITY, &HELPER_ENTITY]);
        let (src1, _) = emit_op_dispatch(&buckets);
        let (src2, _) = emit_op_dispatch(&buckets);
        assert_eq!(src1, src2, "emit_op_dispatch must be deterministic");
    }

    #[test]
    fn emit_op_dispatch_recipe_dedup_collapses_identical_profiles() {
        // Two helpers on different entities with no special fields → both get
        // entity=1 only → same recipe_id → one RECIPE_* const, two Op entries.
        const HELPER_A: OdooMethod = OdooMethod {
            name: "_prepare_a",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        };
        const HELPER_B: OdooMethod = OdooMethod {
            name: "_prepare_b",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        };
        const ENTITY_WITH_TWO_HELPERS: OdooEntity = OdooEntity {
            model_name: "test.two_helpers",
            kind: OdooEntityKind::Model,
            description: "Two identical-profile helpers",
            fields: &[],
            methods: &[HELPER_A, HELPER_B],
            decorators: &[],
            state_machine: None,
            constraints: &[],
            provenance: EMPTY_PROVENANCE,
        };

        let buckets = bucket_corpus(&[&ENTITY_WITH_TWO_HELPERS]);
        assert_eq!(buckets.len(), 2, "two methods");
        // Both get the same recipe_id
        assert_eq!(
            buckets[0].recipe.recipe_id, buckets[1].recipe.recipe_id,
            "identical profiles collapse to one recipe_id"
        );

        let (src, stats) = emit_op_dispatch(&buckets);
        // One unique recipe const
        assert_eq!(stats.unique_recipes, 1, "one unique recipe_id");
        // But two Op entries in the static slice
        assert!(src.contains("_prepare_a"), "_prepare_a in HELPER_OPS");
        assert!(src.contains("_prepare_b"), "_prepare_b in HELPER_OPS");
        // Only one RECIPE_* const emitted
        let recipe_count = src.matches("pub const RECIPE_").count();
        assert_eq!(
            recipe_count, 1,
            "exactly one RECIPE_* const for the collapsed pair"
        );
    }

    #[test]
    fn emit_op_dispatch_ops_sorted_by_recipe_id_then_method_id() {
        // Multi-entity corpus: sort order is deterministic.
        let buckets = bucket_corpus(&[&TEST_ENTITY, &HELPER_ENTITY]);
        let (src, _) = emit_op_dispatch(&buckets);

        // Spot-check: COMPUTE_OPS entry appears before ACTION_OPS entry in
        // the source (bucket declaration order: Compute=0, Action=4).
        let compute_pos = src.find("pub static COMPUTE_OPS").unwrap();
        let action_pos = src.find("pub static ACTION_OPS").unwrap();
        assert!(
            compute_pos < action_pos,
            "Compute bucket before Action bucket"
        );
    }

    #[test]
    fn kind_ord_is_injective_over_all_variants() {
        // All 10 variants map to distinct ordinals.
        use std::collections::BTreeSet;
        let ords: BTreeSet<u8> = [
            OdooMethodKind::Compute,
            OdooMethodKind::Inverse,
            OdooMethodKind::Constrain,
            OdooMethodKind::Onchange,
            OdooMethodKind::Action,
            OdooMethodKind::Cron,
            OdooMethodKind::ApiModel,
            OdooMethodKind::ApiModelCreateMulti,
            OdooMethodKind::Override,
            OdooMethodKind::Helper,
        ]
        .iter()
        .map(|k| kind_ord(*k))
        .collect();
        assert_eq!(ords.len(), 10, "all 10 variants have distinct ordinals");
    }

    #[test]
    fn kind_ord_roundtrips_via_from_ord() {
        for ord in 0u8..10 {
            let k = kind_from_ord(ord);
            assert_eq!(kind_ord(k), ord, "roundtrip for ord={ord}");
        }
    }

    #[test]
    fn atom_comment_empty_recipe_reports_empty() {
        // Construct a recipe with no atoms (impossible in practice but
        // the helper should handle it gracefully).
        let recipe = OdooStyleRecipe {
            method_id: "test.entity._noop".to_owned(),
            atoms: vec![],
            regulation_iris: vec![],
            return_kind: OdooReturnKind::Unit,
            recipe_id: 0,
        };
        assert_eq!(atom_comment(&recipe), "empty");
    }

    #[test]
    fn atom_comment_formats_weights() {
        let recipe = OdooStyleRecipe {
            method_id: "test.entity._compute_x".to_owned(),
            atoms: vec![(DAtom::Entity, 1), (DAtom::Compute, 4)],
            regulation_iris: vec![],
            return_kind: OdooReturnKind::Unit,
            recipe_id: 0,
        };
        assert_eq!(atom_comment(&recipe), "entity=1 compute=4");
    }
}
