//! Auto-generated from /home/user/odoo/addons/analytic/ by `tools/odoo-blueprint-extractor`.
//! Do NOT edit by hand — re-run the extractor.
//! Plan: `.claude/plans/odoo-source-extraction-v1.md` (D-ODOO-EXT-2).

use crate::odoo_blueprint::*;

pub const EXT_ACCOUNT_ANALYTIC_ACCOUNT: OdooEntity = OdooEntity {
    model_name: "account.analytic.account",
    kind: OdooEntityKind::Model,
    description: "Analytic Account",
    fields: &[
        OdooField {
            name: "name",
            kind: OdooFieldKind::Char,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "code",
            kind: OdooFieldKind::Char,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "active",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "plan_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.analytic.plan"),
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "root_plan_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.analytic.plan"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "color",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "line_ids",
            kind: OdooFieldKind::One2many,
            target: Some("account.analytic.line"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.company"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "balance",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_debit_credit_balance"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "debit",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_debit_credit_balance"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "credit",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_debit_credit_balance"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "currency_id",
            kind: OdooFieldKind::Many2one,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_check_company_consistency",
            kind: OdooMethodKind::Constrain,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_display_name",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "copy_data",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "web_read",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_read_group_select",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_read_group_postprocess_aggregate",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_debit_credit_balance",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_update_accounts_in_analytic_lines",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "write",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Boolean,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiConstrains,
            targets: &["company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["code", "partner_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["line_ids.amount"],
        },
    ],
    state_machine: None,
    constraints: &[OdooConstraint {
        kind: OdooConstraintKind::Python,
        condition: "Python constraint on company_id",
        source_method: Some("_check_company_consistency"),
    }],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/analytic_account.py",
            line_range: (11, 243),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &["ogit:regulation/de/ustg/13"],
    },
};

pub const EXT_ACCOUNT_ANALYTIC_DISTRIBUTION_MODEL: OdooEntity = OdooEntity {
    model_name: "account.analytic.distribution.model",
    kind: OdooEntityKind::Model,
    description: "Analytic Distribution Model",
    fields: &[
        OdooField {
            name: "sequence",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_category_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner.category"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.company"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_check_company_accounts",
            kind: OdooMethodKind::Constrain,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_distribution",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_default_search_domain_vals",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_applicable_models",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_create_domain",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiConstrains,
            targets: &["company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[OdooConstraint {
        kind: OdooConstraintKind::Python,
        condition: "Python constraint on company_id",
        source_method: Some("_check_company_accounts"),
    }],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/analytic_distribution_model.py",
            line_range: (9, 96),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ANALYTIC_PLAN_FIELDS_MIXIN: OdooEntity = OdooEntity {
    model_name: "analytic.plan.fields.mixin",
    kind: OdooEntityKind::Abstract,
    description: "Analytic Plan Fields",
    fields: &[
        OdooField {
            name: "account_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.analytic.account"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "auto_account_id",
            kind: OdooFieldKind::Computed,
            target: Some("account.analytic.account"),
            required: false,
            computed: Some("_compute_auto_account"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_compute_auto_account",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_partner_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_inverse_auto_account",
            kind: OdooMethodKind::Inverse,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_search_auto_account",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_plan_fnames",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_analytic_accounts",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_distribution_key",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_analytic_distribution",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_mandatory_plans",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_plan_domain",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_account_node_context",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_check_account_id",
            kind: OdooMethodKind::Constrain,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "default_get",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "fields_get",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_view",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_patch_view",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiConstrains,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[OdooConstraint {
        kind: OdooConstraintKind::Python,
        condition: "Python constraint",
        source_method: Some("_check_account_id"),
    }],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/analytic_line.py",
            line_range: (11, 160),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ACCOUNT_ANALYTIC_LINE: OdooEntity = OdooEntity {
    model_name: "account.analytic.line",
    kind: OdooEntityKind::Model,
    description: "Analytic Line",
    fields: &[
        OdooField {
            name: "name",
            kind: OdooFieldKind::Char,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date",
            kind: OdooFieldKind::Date,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "amount",
            kind: OdooFieldKind::Monetary,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "unit_amount",
            kind: OdooFieldKind::Float,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_uom_id",
            kind: OdooFieldKind::Many2one,
            target: Some("uom.uom"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "user_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.users"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.company"),
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "currency_id",
            kind: OdooFieldKind::Many2one,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "category",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "fiscal_year_search",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "analytic_distribution",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_analytic_distribution"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "analytic_precision",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_compute_analytic_distribution",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_inverse_analytic_distribution",
            kind: OdooMethodKind::Inverse,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_split_amount_fname",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_search_fiscal_date",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[],
    state_machine: None,
    constraints: &[],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/analytic_line.py",
            line_range: (163, 274),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ANALYTIC_MIXIN: OdooEntity = OdooEntity {
    model_name: "analytic.mixin",
    kind: OdooEntityKind::Abstract,
    description: "Analytic Mixin",
    fields: &[
        OdooField {
            name: "analytic_distribution",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_analytic_distribution"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "analytic_precision",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "distribution_analytic_account_ids",
            kind: OdooFieldKind::Computed,
            target: Some("account.analytic.account"),
            required: false,
            computed: Some("_compute_distribution_analytic_account_ids"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "init",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_query_analytic_accounts",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_analytic_account_ids_from_distributions",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_distribution_analytic_account_ids",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_search_distribution_analytic_account_ids",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_analytic_distribution",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_search_analytic_distribution",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_read_group_groupby",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_read_group_select",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_count_id",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "filtered_domain",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "write",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Boolean,
            triggers: &[],
        },
        OdooMethod {
            name: "create",
            kind: OdooMethodKind::ApiModelCreateMulti,
            return_kind: OdooReturnKind::Record,
            triggers: &[],
        },
        OdooMethod {
            name: "_validate_distribution",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_sanitize_values",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_modifiying_distribution_values",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_merge_distribution",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["analytic_distribution"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModelCreateMulti,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/analytic_mixin.py",
            line_range: (12, 275),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ACCOUNT_ANALYTIC_PLAN: OdooEntity = OdooEntity {
    model_name: "account.analytic.plan",
    kind: OdooEntityKind::Model,
    description: "Analytic Plans",
    fields: &[
        OdooField {
            name: "name",
            kind: OdooFieldKind::Char,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "description",
            kind: OdooFieldKind::Text,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "parent_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.analytic.plan"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "parent_path",
            kind: OdooFieldKind::Char,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "root_id",
            kind: OdooFieldKind::Computed,
            target: Some("account.analytic.plan"),
            required: false,
            computed: Some("_compute_root_id"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "children_ids",
            kind: OdooFieldKind::One2many,
            target: Some("account.analytic.plan"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "children_count",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_children_count"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "complete_name",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_complete_name"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "account_ids",
            kind: OdooFieldKind::One2many,
            target: Some("account.analytic.account"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "account_count",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_analytic_account_count"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "all_account_count",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_all_analytic_account_count"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "color",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "sequence",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "default_applicability",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "applicability_ids",
            kind: OdooFieldKind::One2many,
            target: Some("account.analytic.applicability"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_default_color",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_auto_init",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "__get_all_plans",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_all_plans",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_strict_column_name",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_column_name",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_inverse_name",
            kind: OdooMethodKind::Inverse,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_inverse_parent_id",
            kind: OdooMethodKind::Inverse,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_root_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_search_root_id",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_complete_name",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_analytic_account_count",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_all_analytic_account_count",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_children_count",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_onchange_parent_id",
            kind: OdooMethodKind::Onchange,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        },
        OdooMethod {
            name: "action_view_analytical_accounts",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "action_view_children_plans",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "get_relevant_plans",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_applicability",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "unlink",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Boolean,
            triggers: &[],
        },
        OdooMethod {
            name: "_hierarchy_name",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_is_subplan_field_used",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_find_plan_column",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_find_related_field",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_sync_all_plan_column",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_sync_plan_column",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "write",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Boolean,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["parent_id", "parent_path"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["name", "parent_id.complete_name"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["account_ids"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["account_ids", "children_ids"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["children_ids"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["parent_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/analytic_plan.py",
            line_range: (14, 390),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ACCOUNT_ANALYTIC_APPLICABILITY: OdooEntity = OdooEntity {
    model_name: "account.analytic.applicability",
    kind: OdooEntityKind::Model,
    description: "Analytic Plan's Applicabilities",
    fields: &[
        OdooField {
            name: "analytic_plan_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.analytic.plan"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "business_domain",
            kind: OdooFieldKind::Selection,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "applicability",
            kind: OdooFieldKind::Selection,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.company"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[OdooMethod {
        name: "_get_score",
        kind: OdooMethodKind::Helper,
        return_kind: OdooReturnKind::Unit,
        triggers: &[],
    }],
    decorators: &[],
    state_machine: None,
    constraints: &[],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/analytic_plan.py",
            line_range: (393, 430),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_IR_CONFIG_PARAMETER: OdooEntity = OdooEntity {
    model_name: "ir.config_parameter",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[],
    methods: &[OdooMethod {
        name: "write",
        kind: OdooMethodKind::Override,
        return_kind: OdooReturnKind::Boolean,
        triggers: &[],
    }],
    decorators: &[],
    state_machine: None,
    constraints: &[],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/ir_config_parameter.py",
            line_range: (7, 28),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_RES_CONFIG_SETTINGS: OdooEntity = OdooEntity {
    model_name: "res.config.settings",
    kind: OdooEntityKind::Transient,
    description: "",
    fields: &[OdooField {
        name: "group_analytic_accounting",
        kind: OdooFieldKind::Boolean,
        target: None,
        required: false,
        computed: None,
        depends: &[],
        semantic_role: OdooSemanticRole::Other,
    }],
    methods: &[],
    decorators: &[],
    state_machine: None,
    constraints: &[],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef {
            path: "odoo/addons/analytic/models/res_config_settings.py",
            line_range: (7, 10),
        }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};
