//! Auto-generated from /home/user/odoo/addons/purchase/ by `tools/odoo-blueprint-extractor`.
//! Do NOT edit by hand — re-run the extractor.
//! Plan: `.claude/plans/odoo-source-extraction-v1.md` (D-ODOO-EXT-2).

use crate::odoo_blueprint::*;

pub const EXT_ACCOUNT_MOVE: OdooEntity = OdooEntity {
    model_name: "account.move",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[
        OdooField {
            name: "purchase_vendor_bill_id",
            kind: OdooFieldKind::Many2one,
            target: Some("purchase.bill.union"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_id",
            kind: OdooFieldKind::Many2one,
            target: Some("purchase.order"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_order_count",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_origin_po_count"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_order_name",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_order_name"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "is_purchase_matched",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_is_purchase_matched"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_warning_text",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_warning_text"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_onchange_purchase_auto_complete",
            kind: OdooMethodKind::Onchange,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        },
        OdooMethod {
            name: "_onchange_partner_id",
            kind: OdooMethodKind::Onchange,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_is_purchase_matched",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_origin_po_count",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_purchase_order_name",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_purchase_warning_text",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_purchase_matching",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "action_view_source_purchase_orders",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "create",
            kind: OdooMethodKind::ApiModelCreateMulti,
            return_kind: OdooReturnKind::Record,
            triggers: &[],
        },
        OdooMethod {
            name: "write",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Boolean,
            triggers: &[],
        },
        OdooMethod {
            name: "_add_purchase_order_lines",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_find_matching_subset_po_lines",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_find_matching_po_and_inv_lines",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_set_purchase_orders",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_match_purchase_orders",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_find_and_set_purchase_orders",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["purchase_vendor_bill_id", "purchase_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["partner_id", "company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["line_ids.purchase_line_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["line_ids.purchase_line_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["purchase_order_count"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["partner_id.name", "partner_id.purchase_warn_msg", "invoice_line_ids.product_id.purchase_line_warn_msg", "invoice_line_ids.product_id.display_name"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModelCreateMulti,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/account_invoice.py", line_range: (16, 518) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ACCOUNT_MOVE_LINE: OdooEntity = OdooEntity {
    model_name: "account.move.line",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[
        OdooField {
            name: "is_downpayment",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_line_id",
            kind: OdooFieldKind::Many2one,
            target: Some("purchase.order.line"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_order_id",
            kind: OdooFieldKind::Many2one,
            target: Some("purchase.order"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_line_warn_msg",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_line_warn_msg"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_copy_data_extend_business_fields",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_line_values_for_purchase",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_related_analytic_distribution",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_purchase_line_warn_msg",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_id.purchase_line_warn_msg"],
        },
    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/account_invoice.py", line_range: (521, 558) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ACCOUNT_TAX: OdooEntity = OdooEntity {
    model_name: "account.tax",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[

    ],
    methods: &[
        OdooMethod {
            name: "_hook_compute_is_used",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[

    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/account_tax.py", line_range: (6, 29) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ACCOUNT_ANALYTIC_ACCOUNT: OdooEntity = OdooEntity {
    model_name: "account.analytic.account",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[
        OdooField {
            name: "purchase_order_count",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_order_count"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_compute_purchase_order_count",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_view_purchase_orders",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["line_ids"],
        },
    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/analytic_account.py", line_range: (7, 34) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_ACCOUNT_ANALYTIC_APPLICABILITY: OdooEntity = OdooEntity {
    model_name: "account.analytic.applicability",
    kind: OdooEntityKind::Model,
    description: "Analytic Plan's Applicabilities",
    fields: &[
        OdooField {
            name: "business_domain",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[

    ],
    decorators: &[

    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/analytic_applicability.py", line_range: (6, 15) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_IR_ACTIONS_REPORT: OdooEntity = OdooEntity {
    model_name: "ir.actions.report",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[

    ],
    methods: &[
        OdooMethod {
            name: "_render_qweb_pdf_prepare_streams",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_is_purchase_order_report",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[

    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/ir_actions_report.py", line_range: (7, 56) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_PRODUCT_TEMPLATE: OdooEntity = OdooEntity {
    model_name: "product.template",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[
        OdooField {
            name: "purchased_product_qty",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchased_product_qty"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_method",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_method"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_line_warn_msg",
            kind: OdooFieldKind::Text,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_compute_purchase_method",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_purchased_product_qty",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_backend_root_menu_ids",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_import_templates",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_view_po",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["type"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/product.py", line_range: (10, 55) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_PRODUCT_PRODUCT: OdooEntity = OdooEntity {
    model_name: "product.product",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[
        OdooField {
            name: "purchased_product_qty",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchased_product_qty"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "is_in_purchase_order",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_is_in_purchase_order"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_compute_purchased_product_qty",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_is_in_purchase_order",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_search_is_in_purchase_order",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_view_po",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_backend_root_menu_ids",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_update_uom",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_trigger_uom_warning",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[

    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/product.py", line_range: (58, 141) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_PRODUCT_SUPPLIERINFO: OdooEntity = OdooEntity {
    model_name: "product.supplierinfo",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[

    ],
    methods: &[
        OdooMethod {
            name: "_onchange_partner_id",
            kind: OdooMethodKind::Onchange,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_filtered_supplier",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["partner_id"],
        },
    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/product.py", line_range: (144, 154) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_PURCHASE_BILL_LINE_MATCH: OdooEntity = OdooEntity {
    model_name: "purchase.bill.line.match",
    kind: OdooEntityKind::Model,
    description: "Purchase Line and Vendor Bill line matching view",
    fields: &[
        OdooField {
            name: "pol_id",
            kind: OdooFieldKind::Many2one,
            target: Some("purchase.order.line"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "aml_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.move.line"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.company"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_id",
            kind: OdooFieldKind::Many2one,
            target: Some("product.product"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "line_qty",
            kind: OdooFieldKind::Float,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "line_uom_id",
            kind: OdooFieldKind::Many2one,
            target: Some("uom.uom"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_invoiced",
            kind: OdooFieldKind::Float,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_to_invoice",
            kind: OdooFieldKind::Float,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_order_id",
            kind: OdooFieldKind::Many2one,
            target: Some("purchase.order"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "account_move_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.move"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "line_amount_untaxed",
            kind: OdooFieldKind::Monetary,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "currency_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.currency"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "state",
            kind: OdooFieldKind::Char,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_uom_id",
            kind: OdooFieldKind::Many2one,
            target: Some("uom.uom"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_uom_qty",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_product_uom_qty"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_uom_price",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_product_uom_price"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "billed_amount_untaxed",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_amount_untaxed_fields"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_amount_untaxed",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_amount_untaxed_fields"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "reference",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_reference"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_inverse_product_uom_price",
            kind: OdooMethodKind::Inverse,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_inverse_product_uom_qty",
            kind: OdooMethodKind::Inverse,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_amount_untaxed_fields",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_reference",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_display_name",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_product_uom_qty",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_product_uom_price",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_select_po_line",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_select_am_line",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_table_query",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_open_line",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "_action_create_bill_from_po_lines",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_match_lines",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "action_add_to_po",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["product_uom_price"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["product_uom_qty"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["aml_id.price_unit", "pol_id.price_unit"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/purchase_bill_line_match.py", line_range: (9, 203) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_PURCHASE_ORDER: OdooEntity = OdooEntity {
    model_name: "purchase.order",
    kind: OdooEntityKind::Model,
    description: "Purchase Order",
    fields: &[
        OdooField {
            name: "name",
            kind: OdooFieldKind::Char,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "priority",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "origin",
            kind: OdooFieldKind::Char,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_ref",
            kind: OdooFieldKind::Char,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date_order",
            kind: OdooFieldKind::Datetime,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date_approve",
            kind: OdooFieldKind::Datetime,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner"),
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "dest_address_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "currency_id",
            kind: OdooFieldKind::Computed,
            target: Some("res.currency"),
            required: true,
            computed: Some("_compute_currency_id"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "state",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "locked",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "lock_confirmed_po",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "order_line",
            kind: OdooFieldKind::One2many,
            target: Some("purchase.order.line"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "acknowledged",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "note",
            kind: OdooFieldKind::Html,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_bill_count",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "invoice_count",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_invoice"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "invoice_ids",
            kind: OdooFieldKind::Computed,
            target: Some("account.move"),
            required: false,
            computed: Some("_compute_invoice"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "invoice_status",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_get_invoiced"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date_planned",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_date_planned"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date_calendar_start",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_date_calendar_start"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "amount_untaxed",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_amount_all"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "tax_totals",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_tax_totals"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "amount_tax",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_amount_all"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "amount_total",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_amount_all"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "amount_total_cc",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_amount_all"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "fiscal_position_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.fiscal.position"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "tax_country_id",
            kind: OdooFieldKind::Computed,
            target: Some("res.country"),
            required: false,
            computed: Some("_compute_tax_country_id"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "tax_calculation_rounding_method",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "payment_term_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.payment.term"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "incoterm_id",
            kind: OdooFieldKind::Many2one,
            target: Some("account.incoterms"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_id",
            kind: OdooFieldKind::Many2one,
            target: Some("product.product"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "user_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.users"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.company"),
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_currency_id",
            kind: OdooFieldKind::Many2one,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "country_code",
            kind: OdooFieldKind::Char,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_price_include",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "currency_rate",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_currency_rate"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "duplicated_order_ids",
            kind: OdooFieldKind::Computed,
            target: Some("purchase.order"),
            required: false,
            computed: Some("_compute_duplicated_order_ids"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "receipt_reminder_email",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_receipt_reminder_email"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "reminder_date_before_receipt",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_receipt_reminder_email"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "is_late",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "show_comparison",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_show_comparison"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_warning_text",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_warning_text"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_amount_all",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_invoiced",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_invoice",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_check_order_line_company_id",
            kind: OdooMethodKind::Constrain,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_access_url",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_date_calendar_start",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_currency_rate",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_amount_total_cc",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_date_planned",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_display_name",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_receipt_reminder_email",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_tax_totals",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_tax_country_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_show_comparison",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_purchase_warning_text",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_duplicated_order_ids",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_fetch_duplicate_orders",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_open_business_doc",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "onchange_date_planned",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_search_is_late",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_domain_is_late",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "create",
            kind: OdooMethodKind::ApiModelCreateMulti,
            return_kind: OdooReturnKind::Record,
            triggers: &[],
        },
        OdooMethod {
            name: "_unlink_if_cancelled",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "copy",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_must_delete_date_planned",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "onchange",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_report_base_filename",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "onchange_partner_id",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_currency_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_tax_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "message_post",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_notify_get_recipients_groups",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_notify_by_email_prepare_rendering_context",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_track_subtype",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_rfq_send",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "action_acknowledge",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "action_purchase_comparison",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "print_quotation",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "button_approve",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "button_draft",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "button_confirm",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "button_cancel",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "button_lock",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "button_unlock",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_confirmation_error_message",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_supplier_info",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_add_supplier_to_product",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_bill_matching",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_down_payment_section_values",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_create_downpayments",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_create_invoice",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "action_merge",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "_merge_po_post_process",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_merge_alternative_po",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_grouped_data",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_invoice",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_view_invoice",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "retrieve_dashboard",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_send_reminder_mail",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "send_reminder_preview",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_send_reminder_open_composer",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_orders_to_remind",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_default_order_line_values",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_add_from_catalog",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_action_add_from_catalog_extra_context",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_product_catalog_domain",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_product_catalog_order_data",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_product_catalog_record_lines",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_product_price_and_data",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_acknowledge_url",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_confirm_url",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_update_url",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_approval_allowed",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_localized_date_planned",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_order_timezone",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_update_date_planned_for_lines",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_update_order_line_info",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_default_create_section_values",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_parent_field_on_child_model",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_create_update_date_activity",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_update_update_date_activity",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_is_readonly",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_import_templates",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_edi_builders",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "create_document_from_attachment",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["order_line.price_subtotal", "company_id", "currency_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["state", "order_line.qty_to_invoice"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["order_line.invoice_lines.move_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiConstrains,
            targets: &["company_id", "order_line"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["state", "date_order", "date_approve"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["currency_id", "date_order", "company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["amount_total", "currency_rate"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["order_line.date_planned"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["name", "partner_ref", "amount_total", "currency_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["company_id", "partner_id", "partner_id.reminder_date_before_receipt"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["order_line.price_subtotal", "currency_id", "company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["company_id.account_fiscal_country_id", "fiscal_position_id.country_id", "fiscal_position_id.foreign_vat"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["order_line", "order_line.product_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["partner_id.name", "partner_id.purchase_warn_msg", "order_line.purchase_line_warn_msg"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["partner_ref", "origin", "partner_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["date_planned"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModelCreateMulti,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["partner_id", "company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["partner_id", "company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["fiscal_position_id", "company_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
    ],
    state_machine: Some(&OdooStateMachine {
            state_field: "state",
            states: &[
                OdooState { name: "draft", semantic: OdooStateSemantic::Draft },
                OdooState { name: "sent", semantic: OdooStateSemantic::Active },
                OdooState { name: "to approve", semantic: OdooStateSemantic::Active },
                OdooState { name: "purchase", semantic: OdooStateSemantic::Active },
                OdooState { name: "cancel", semantic: OdooStateSemantic::Cancelled },
            ],
            transitions: &[
            ],
        }),
    constraints: &[
        OdooConstraint {
            kind: OdooConstraintKind::Python,
            condition: "Python constraint on company_id, order_line",
            source_method: Some("_check_order_line_company_id"),
        },
    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/purchase_order.py", line_range: (21, 1418) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_PURCHASE_ORDER_LINE: OdooEntity = OdooEntity {
    model_name: "purchase.order.line",
    kind: OdooEntityKind::Model,
    description: "Purchase Order Line",
    fields: &[
        OdooField {
            name: "name",
            kind: OdooFieldKind::Computed,
            target: None,
            required: true,
            computed: Some("_compute_price_unit_and_date_planned_and_name"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "translated_product_name",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_translated_product_name"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "sequence",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_qty",
            kind: OdooFieldKind::Float,
            target: None,
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_uom_qty",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_product_uom_qty"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date_planned",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_price_unit_and_date_planned_and_name"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "discount",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_price_unit_and_date_planned_and_name"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "tax_ids",
            kind: OdooFieldKind::Many2many,
            target: Some("account.tax"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "allowed_uom_ids",
            kind: OdooFieldKind::Computed,
            target: Some("uom.uom"),
            required: false,
            computed: Some("_compute_allowed_uom_ids"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_uom_id",
            kind: OdooFieldKind::Many2one,
            target: Some("uom.uom"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_id",
            kind: OdooFieldKind::Many2one,
            target: Some("product.product"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_type",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "price_unit",
            kind: OdooFieldKind::Computed,
            target: None,
            required: true,
            computed: Some("_compute_price_unit_and_date_planned_and_name"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "price_unit_product_uom",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_price_unit_product_uom"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "price_unit_discounted",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_price_unit_discounted"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "price_subtotal",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_amount"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "price_total",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_amount"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "price_tax",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_amount"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "order_id",
            kind: OdooFieldKind::Many2one,
            target: Some("purchase.order"),
            required: true,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.company"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "state",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "invoice_lines",
            kind: OdooFieldKind::One2many,
            target: Some("account.move.line"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_invoiced",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_qty_invoiced"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_received_method",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_qty_received_method"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_received",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_qty_received"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_received_manual",
            kind: OdooFieldKind::Float,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_to_invoice",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_qty_invoiced"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_received_at_date",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_qty_received_at_date"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "qty_invoiced_at_date",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_qty_invoiced_at_date"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "amount_to_invoice_at_date",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_amount_to_invoice_at_date"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "partner_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.partner"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "currency_id",
            kind: OdooFieldKind::Many2one,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date_order",
            kind: OdooFieldKind::Datetime,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "date_approve",
            kind: OdooFieldKind::Datetime,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "tax_calculation_rounding_method",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "display_type",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "is_downpayment",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "selected_seller_id",
            kind: OdooFieldKind::Computed,
            target: Some("product.supplierinfo"),
            required: false,
            computed: Some("_compute_selected_seller_id"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_template_attribute_value_ids",
            kind: OdooFieldKind::Many2many,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "product_no_variant_attribute_value_ids",
            kind: OdooFieldKind::Many2many,
            target: Some("product.template.attribute.value"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_line_warn_msg",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_line_warn_msg"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "parent_id",
            kind: OdooFieldKind::Computed,
            target: Some("purchase.order.line"),
            required: false,
            computed: Some("_compute_parent_id"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "technical_price_unit",
            kind: OdooFieldKind::Float,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_compute_amount",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_base_line_for_taxes_computation",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_tax_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_price_unit_discounted",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_price_unit_product_uom",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_qty_invoiced",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_qty_invoiced_at_date",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_qty_invoiced",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_invoice_lines",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_purchase_line_warn_msg",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_qty_received_method",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_qty_received",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_qty_received_at_date",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_qty_received",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_inverse_qty_received",
            kind: OdooMethodKind::Inverse,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_selected_seller_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_amount_to_invoice_at_date",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "create",
            kind: OdooMethodKind::ApiModelCreateMulti,
            return_kind: OdooReturnKind::Record,
            triggers: &[],
        },
        OdooMethod {
            name: "write",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Boolean,
            triggers: &[],
        },
        OdooMethod {
            name: "_unlink_except_purchase",
            kind: OdooMethodKind::Override,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_date_planned",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_analytic_distribution",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "onchange_product_id",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_product_id_change",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_allowed_uom_ids",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_price_unit_and_date_planned_and_name",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_translated_product_name",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_product_uom_qty",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_gross_price_unit",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_parent_id",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_add_from_catalog",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "_suggest_quantity",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_product_catalog_lines_data",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_product_purchase_description",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_account_move_line",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_add_missing_fields",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_prepare_purchase_order_line",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_convert_to_middle_of_day",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_date_in_the_past",
            kind: OdooMethodKind::ApiModel,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_update_date_planned",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_track_qty_received",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_validate_analytic_distribution",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "action_open_order",
            kind: OdooMethodKind::Action,
            return_kind: OdooReturnKind::Action,
            triggers: &[],
        },
        OdooMethod {
            name: "_merge_po_line",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_get_select_sellers_params",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "get_parent_section_line",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_qty", "price_unit", "tax_ids", "discount"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["discount", "price_unit"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_uom_id", "price_unit"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["invoice_lines.move_id.state", "invoice_lines.quantity", "qty_received", "product_uom_qty", "order_id.state"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["qty_invoiced"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_id.purchase_line_warn_msg"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_id", "product_id.type"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["qty_received_method", "qty_received_manual"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["qty_received"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["qty_received"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_id", "product_id.seller_ids", "partner_id", "product_qty", "order_id.date_order", "product_uom_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["price_unit", "qty_invoiced_at_date", "qty_received_at_date"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModelCreateMulti,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_id", "order_id.partner_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["product_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_id", "product_id.uom_id", "product_id.uom_ids", "product_id.seller_ids", "product_id.seller_ids.product_uom_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_qty", "product_uom_id", "company_id", "order_id.partner_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiDepends,
            targets: &["product_uom_id", "product_qty", "product_id.uom_id"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiModel,
            targets: &[],
        },
    ],
    state_machine: None,
    constraints: &[
        OdooConstraint {
            kind: OdooConstraintKind::Sql,
            condition: "Missing required fields on accountable purchase order line.",
            source_method: None,
        },
        OdooConstraint {
            kind: OdooConstraintKind::Sql,
            condition: "Forbidden values on non-accountable purchase order line",
            source_method: None,
        },
    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/purchase_order_line.py", line_range: (13, 753) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_RES_COMPANY: OdooEntity = OdooEntity {
    model_name: "res.company",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[
        OdooField {
            name: "po_lock",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "po_double_validation",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "po_double_validation_amount",
            kind: OdooFieldKind::Monetary,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[

    ],
    decorators: &[

    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/res_company.py", line_range: (7, 23) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &["ogit:regulation/eu/en16931"],
    },
};

pub const EXT_RES_CONFIG_SETTINGS: OdooEntity = OdooEntity {
    model_name: "res.config.settings",
    kind: OdooEntityKind::Transient,
    description: "",
    fields: &[
        OdooField {
            name: "lock_confirmed_po",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "po_lock",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "po_order_approval",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "po_double_validation",
            kind: OdooFieldKind::Selection,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "po_double_validation_amount",
            kind: OdooFieldKind::Monetary,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "company_currency_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.currency"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "group_warning_purchase",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "module_account_3way_match",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "module_purchase_requisition",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "module_purchase_product_matrix",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "group_send_reminder",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_onchange_group_product_variant_purchase",
            kind: OdooMethodKind::Onchange,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        },
        OdooMethod {
            name: "_onchange_module_purchase_product_matrix",
            kind: OdooMethodKind::Onchange,
            return_kind: OdooReturnKind::Dict,
            triggers: &[],
        },
        OdooMethod {
            name: "set_values",
            kind: OdooMethodKind::Helper,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["group_product_variant"],
        },
        OdooDecorator {
            kind: OdooDecoratorKind::ApiOnchange,
            targets: &["module_purchase_product_matrix"],
        },
    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/res_config_settings.py", line_range: (7, 44) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

pub const EXT_RES_PARTNER: OdooEntity = OdooEntity {
    model_name: "res.partner",
    kind: OdooEntityKind::Model,
    description: "",
    fields: &[
        OdooField {
            name: "property_purchase_currency_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.currency"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_order_count",
            kind: OdooFieldKind::Computed,
            target: None,
            required: false,
            computed: Some("_compute_purchase_order_count"),
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "purchase_warn_msg",
            kind: OdooFieldKind::Text,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "receipt_reminder_email",
            kind: OdooFieldKind::Boolean,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "reminder_date_before_receipt",
            kind: OdooFieldKind::Integer,
            target: None,
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
        OdooField {
            name: "buyer_id",
            kind: OdooFieldKind::Many2one,
            target: Some("res.users"),
            required: false,
            computed: None,
            depends: &[],
            semantic_role: OdooSemanticRole::Other,
        },
    ],
    methods: &[
        OdooMethod {
            name: "_compute_purchase_order_count",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
        OdooMethod {
            name: "_compute_application_statistics_hook",
            kind: OdooMethodKind::Compute,
            return_kind: OdooReturnKind::Unit,
            triggers: &[],
        },
    ],
    decorators: &[

    ],
    state_machine: None,
    constraints: &[

    ],
    provenance: OdooProvenance {
        l_doc: "",
        l_doc_lines: (0, 0),
        odoo_source: &[OdooSourceRef { path: "odoo/addons/purchase/models/res_partner.py", line_range: (6, 54) }],
        confidence: OdooConfidence::Extracted,
        regulation_iri: &[],
    },
};

