//! The deterministic ERP-shaped fixture the DuckDB differential suite runs
//! against — three tables, generated by a seeded splitmix64 stream so the
//! same bytes come out of every run, in every environment, forever.
//!
//! Foreign keys are ROW INDICES, not a minted address: `line.doc_id` names a
//! `doc` row by its position, `line.partner_id` names a `partner` row by its
//! position, and both tables carry an explicit `rid` column in their CSV so
//! a consumer (DuckDB or this crate) never has to trust an engine's own
//! internal row-numbering to agree with the fixture's.
//!
//! This module is included by `#[path]` from `duckdb_differential.rs`, not
//! compiled as its own test binary — `cargo test` only auto-discovers files
//! directly under `tests/`, so a file one level down (here) is inert until
//! named.

use std::io::{self, Write};
use std::path::Path;

use lance_graph_mask_risc::{LaneRef, Planes};

/// Row counts — the shapes named in the spec.
pub const PARTNER_ROWS: usize = 64;
pub const DOC_ROWS: usize = 512;
pub const LINE_ROWS: usize = 4096;

/// splitmix64: the whole generator. One state word, one step.
fn splitmix64(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = *state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Uniform `0..n`. Modulo bias is not a concern here — the fixture only
/// needs to be FIXED, not statistically pure.
fn next_u32(state: &mut u64, n: u32) -> u32 {
    (splitmix64(state) % u64::from(n)) as u32
}

/// Uniform `[lo, hi)` as `i32`.
fn next_i32_range(state: &mut u64, lo: i32, hi: i32) -> i32 {
    lo + next_u32(state, (hi - lo) as u32) as i32
}

/// `status` weighted 20 % open / 70 % posted / 10 % cancelled.
fn next_status(state: &mut u64) -> u32 {
    let r = next_u32(state, 100);
    if r < 20 {
        0
    } else if r < 90 {
        1
    } else {
        2
    }
}

const GL_ACCOUNTS: [u32; 4] = [400_000, 410_000, 500_000, 600_000];

fn next_gl_account(state: &mut u64) -> u32 {
    GL_ACCOUNTS[next_u32(state, GL_ACCOUNTS.len() as u32) as usize]
}

/// The `partner` table — 64 rows, `country: 0..8`, `pgroup: 0..4`.
pub struct PartnerTable {
    pub country: Vec<u32>,
    pub pgroup: Vec<u32>,
}

/// The `doc` table — 512 rows, `company: 0..3`, `period: 1..13`,
/// `doc_type: 0..4`.
pub struct DocTable {
    pub company: Vec<u32>,
    pub period: Vec<u32>,
    pub doc_type: Vec<u32>,
}

/// The `line` table — 4096 rows.
///
/// `doc_id` is stored as `i32`, not `u32`, and that is a deliberate
/// representational choice made HERE, not a fact about the schema: the
/// fixture's `doc_id` domain is `0..DOC_ROWS`, always non-negative and far
/// inside `i32`'s range, so nothing is lost by the cast. It is needed because
/// `lance_graph_mask_risc::Pred` has ordered comparisons (`GtI32`/`LtI32`/…)
/// only over a signed lane — there is no `GtU32`/`LtU32` in the IR today — and
/// `range_docid` is exactly the query that needs one. Every other `line`
/// column that participates in a lowered query is compared by EQUALITY or by
/// [`lance_graph_quack::Cmp::MatchU32`]'s ternary match, neither of which
/// needs an order, so they stay `u32`, matching the schema's own typing.
pub struct LineTable {
    pub doc_id: Vec<i32>,
    /// `doc_id`, again, but `u32` — the fk shape [`MaskOp::Gather`] /
    /// [`Terminal::ScatterOrU32`] need (their lane must be
    /// [`LaneKind::U32`](lance_graph_mask_risc::LaneKind::U32); `doc_id`
    /// stays `i32` above for `range_docid`'s ordered compare). Same values,
    /// cast at generation time — the fixture's `doc_id` domain is always
    /// `0..DOC_ROWS`, so the cast loses nothing.
    pub doc_id_u32: Vec<u32>,
    pub partner_id: Vec<u32>,
    pub amount: Vec<i32>,
    pub qty: Vec<i32>,
    pub status: Vec<u32>,
    pub cost_center: Vec<u32>,
    pub gl_account: Vec<u32>,
}

pub struct Fixture {
    pub partner: PartnerTable,
    pub doc: DocTable,
    pub line: LineTable,
}

/// The seed, spelled as a valid hex literal (hex digits only: no `O`, no `L`
/// — `FOLD` becomes `F01D`, the ordinary leetspeak substitution).
const SEED: u64 = 0x51AC_F01D_2026;

/// Generate the fixture. Deterministic: the same seed, the same row-major
/// draw order (every field of row `i` before any field of row `i + 1`, table
/// by table: `partner`, then `doc`, then `line`), every time.
pub fn generate() -> Fixture {
    let mut state = SEED;

    let mut country = Vec::with_capacity(PARTNER_ROWS);
    let mut pgroup = Vec::with_capacity(PARTNER_ROWS);
    for _ in 0..PARTNER_ROWS {
        country.push(next_u32(&mut state, 8));
        pgroup.push(next_u32(&mut state, 4));
    }
    let partner = PartnerTable { country, pgroup };

    let mut company = Vec::with_capacity(DOC_ROWS);
    let mut period = Vec::with_capacity(DOC_ROWS);
    let mut doc_type = Vec::with_capacity(DOC_ROWS);
    for _ in 0..DOC_ROWS {
        company.push(next_u32(&mut state, 3));
        period.push(next_u32(&mut state, 12) + 1);
        doc_type.push(next_u32(&mut state, 4));
    }
    let doc = DocTable {
        company,
        period,
        doc_type,
    };

    let mut doc_id = Vec::with_capacity(LINE_ROWS);
    let mut partner_id = Vec::with_capacity(LINE_ROWS);
    let mut amount = Vec::with_capacity(LINE_ROWS);
    let mut qty = Vec::with_capacity(LINE_ROWS);
    let mut status = Vec::with_capacity(LINE_ROWS);
    let mut cost_center = Vec::with_capacity(LINE_ROWS);
    let mut gl_account = Vec::with_capacity(LINE_ROWS);
    for _ in 0..LINE_ROWS {
        doc_id.push(next_i32_range(&mut state, 0, DOC_ROWS as i32));
        partner_id.push(next_u32(&mut state, PARTNER_ROWS as u32));
        amount.push(next_i32_range(&mut state, -5000, 20_000));
        qty.push(next_i32_range(&mut state, 1, 50));
        status.push(next_status(&mut state));
        cost_center.push(next_u32(&mut state, 8));
        gl_account.push(next_gl_account(&mut state));
    }
    // Derived, not drawn: no RNG state is consumed here, so this can never
    // shift any later draw or desync the committed CSVs / DuckDB `expected`
    // values from the generator.
    let doc_id_u32: Vec<u32> = doc_id.iter().map(|&d| d as u32).collect();
    let line = LineTable {
        doc_id,
        doc_id_u32,
        partner_id,
        amount,
        qty,
        status,
        cost_center,
        gl_account,
    };

    Fixture { partner, doc, line }
}

impl Fixture {
    /// `partner.csv`'s bytes, in memory — the single source both the
    /// on-disk writer and the drift guard read from, so there is exactly one
    /// place the format can drift.
    pub fn partner_csv(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        writeln!(buf, "rid,country,pgroup").expect("write to Vec never fails");
        for i in 0..PARTNER_ROWS {
            writeln!(
                buf,
                "{i},{},{}",
                self.partner.country[i], self.partner.pgroup[i]
            )
            .expect("write to Vec never fails");
        }
        buf
    }

    /// `doc.csv`'s bytes. See [`Fixture::partner_csv`].
    pub fn doc_csv(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        writeln!(buf, "rid,company,period,doc_type").expect("write to Vec never fails");
        for i in 0..DOC_ROWS {
            writeln!(
                buf,
                "{i},{},{},{}",
                self.doc.company[i], self.doc.period[i], self.doc.doc_type[i]
            )
            .expect("write to Vec never fails");
        }
        buf
    }

    /// `line.csv`'s bytes. See [`Fixture::partner_csv`].
    pub fn line_csv(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        writeln!(
            buf,
            "rid,doc_id,partner_id,amount,qty,status,cost_center,gl_account"
        )
        .expect("write to Vec never fails");
        for i in 0..LINE_ROWS {
            writeln!(
                buf,
                "{i},{},{},{},{},{},{},{}",
                self.line.doc_id[i],
                self.line.partner_id[i],
                self.line.amount[i],
                self.line.qty[i],
                self.line.status[i],
                self.line.cost_center[i],
                self.line.gl_account[i],
            )
            .expect("write to Vec never fails");
        }
        buf
    }

    /// Write `partner.csv` / `doc.csv` / `line.csv` into `dir` — the
    /// generator's on-disk form, built once and committed under
    /// `tests/duckdb/data/`. Byte-for-byte deterministic: the drift guard
    /// (`committed_fixture_matches_generator`) depends on that.
    pub fn write_csv(&self, dir: &Path) -> io::Result<()> {
        std::fs::write(dir.join("partner.csv"), self.partner_csv())?;
        std::fs::write(dir.join("doc.csv"), self.doc_csv())?;
        std::fs::write(dir.join("line.csv"), self.line_csv())?;
        Ok(())
    }
}

/// The `line` table's lanes, in the fixed order the `Col` constants below
/// index into. `line` is the table every lowered [`lance_graph_quack::Query`]
/// runs against; `partner` is now ALSO exposed as [`Planes`] (see
/// [`col::partner`]) so the two join cases can lower a real partner-side
/// filter to a real `Program` — `doc` still exists only as CSV rows for the
/// oracle, since no case in this suite filters it directly.
pub mod col {
    use lance_graph_quack::Col;

    pub const AMOUNT: Col = Col(0);
    pub const QTY: Col = Col(1);
    pub const DOC_ID: Col = Col(2);
    pub const STATUS: Col = Col(3);
    pub const COST_CENTER: Col = Col(4);
    pub const GL_ACCOUNT: Col = Col(5);
    /// `line.partner_id`, `u32` — the fk into `partner` (`p.rid`), the
    /// lane [`lance_graph_mask_risc::MaskOp::Gather`] needs.
    pub const PARTNER_ID: Col = Col(6);
    /// `line.doc_id`, `u32` — see [`super::LineTable::doc_id_u32`]. The
    /// same value as [`DOC_ID`], cast; `DOC_ID` stays for `range_docid`'s
    /// ordered compare.
    pub const DOC_ID_U32: Col = Col(7);
}

/// The `line` table's lanes, borrowed and held so [`Planes`] can borrow them
/// back in turn. Two steps because `Planes<'a>` needs `&'a [LaneRef<'a>]` —
/// an array built inline in a function cannot outlive that function's
/// return, so this struct is the thing that DOES outlive it, owned by the
/// caller for exactly as long as the [`Planes`] it lends out.
pub struct LineLanes<'a> {
    lanes: [LaneRef<'a>; 8],
}

impl LineTable {
    /// Borrow every lane in the fixed order `col` above indexes into.
    pub fn lanes(&self) -> LineLanes<'_> {
        LineLanes {
            lanes: [
                LaneRef::I32(&self.amount),
                LaneRef::I32(&self.qty),
                LaneRef::I32(&self.doc_id),
                LaneRef::U32(&self.status),
                LaneRef::U32(&self.cost_center),
                LaneRef::U32(&self.gl_account),
                LaneRef::U32(&self.partner_id),
                LaneRef::U32(&self.doc_id_u32),
            ],
        }
    }
}

// The `partner` table is never run as its own `Planes`: its lanes are read
// THROUGH `line.partner_id` (`Filter::EqU32Via`, `Agg::GroupSumViaI32`) as
// `Foreign::lanes`, so no partner-side program — and no partner-side kept
// mask — ever exists. `pgroup` stays generated for the DuckDB oracle only.

impl<'a> LineLanes<'a> {
    /// Borrow `LINE_ROWS` rows over these lanes, no resident mask planes —
    /// every case in this suite is a plain `WHERE`, never a plane leaf.
    pub fn planes(&self) -> Planes<'_> {
        Planes {
            n_rows: LINE_ROWS,
            masks: &[],
            lanes: &self.lanes,
        }
    }
}
